DOC: Do not complain about contiguity when mutating `ndarray.shape`
numpy/numpy pull request #10600
Opened 2018-02-15 19:59 UTC by hanjohn

There are multiple conditions that `_attempt_nocopy_reshape` checks for
when ndarray.shape is mutated directly. Discussion of #10146 indicated
that an error message referencing any type of contiguity would not be
correct for all cases, so the error message has been changed to be more
general.

2018-02-15 20:02 UTC, eric-wieser commented
Unrelated, but this sure feels like it should be raising `ValueError` - don't worry about it in this patch though

2018-02-16 05:46 UTC, eric-wieser commented
Can we get the word "in-place" into the error message somehow?

2020-02-27 07:54 UTC, mattip commented
@eric-wieser I rebased off master and shortened the error message. Does "Incompatible shape for in-place modifcation. Use`.reshape()` to make a copy with the desired shape." seem reasonable?

2020-03-09 11:32 UTC, eric-wieser commented on numpy/core/src/multiarray/getset.c
> +                        "Incompatible shape for in-place modifcation. Use "
```suggestion
                        "Incompatible shape for in-place modification. Use "
```

2020-03-11 13:29 UTC, panpiort8 commented on numpy/core/_add_newdocs.py
> +    AttributeError: Incompatible shape for in-place modifcation. Use
```suggestion
    AttributeError: Incompatible shape for in-place modification. Use
```

2020-03-11 13:33 UTC, panpiort8 requested changes
I think it'll fix checks errors.

2020-03-11 13:33 UTC, panpiort8 commented on numpy/core/fromnumeric.py
> +     AttributeError: Incompatible shape for in-place modifcation. Use
```suggestion
     AttributeError: Incompatible shape for in-place modification. Use
```

2020-03-11 13:33 UTC, panpiort8 commented on numpy/core/_add_newdocs.py
> +    AttributeError: Incompatible shape for in-place modifcation. Use
```suggestion
    AttributeError: Incompatible shape for in-place modification. Use
```

2020-03-12 06:54 UTC, mattip commented
fixed typos, thanks @panpiort8

2020-03-12 07:35 UTC, eric-wieser approved these changes

2020-03-12 16:51 UTC, seberg commented
LGTM as well, thanks.

2020-03-12 16:52 UTC, merged