WIP: DOC: rework documents and silence warnings during sphinx build
numpy/numpy pull request #10878
Opened 2018-04-10 18:50 UTC by mattip

This started with the first two commits which make the devdocs more prominent and add the howto_build and howto_docuement to the public document tree.

I then noticed all the warnings produced during documentation generation. It seems that the plots in `random` require scipy.special to produce the theoretical distribution alongside the sampled distribution.
There are still many more warnings, see the [circleci build](https://circleci.com/gh/numpy/numpy/958?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

Should I split this into separate smaller pull requests? I still would like to silence more of the warnings, so this is still a WIP

2018-04-11 02:26 UTC, rgommers commented
These changes are very welcome, thanks!

Installing `scipy` for the doc build is fine with me. We also require `matplotlib`; dependencies for building docs aren't a big deal imho.

Splitting in multiple PRs isn't strictly necessary, but this can be merged now. Maybe make a difference between changes like adding a dependency, and keeping large diffs due to warning fixes in a separate PR?

2018-04-11 02:28 UTC, rgommers requested changes
The `HOWTO_DOCUMENT` is linked to directly in many places, so needs a redirect. The `HOWTO_BUILD` doesn't I think. Other than that, this looks good.

2018-04-11 02:28 UTC, rgommers commented on doc/source/docs/howto_build_docs.rst
> +module require `scipy.scpecial` to display properly. Now you are ready to
typo `scpecial`

2018-04-11 02:45 UTC, njsmith commented
It would be great if we can eventually turn on `-W`, sphinx's convert-warnings-into-errors mode, since sphinx's idea of a "warning" is universally actually a bug. Doesn't have to be this PR though, I just wanted to mention its existence since I only recently learned about it :-)

2018-04-11 07:37 UTC, mattip commented
> turn on -W, sphinx's convert-warnings-into-errors mode

Is it on for docstring tests? Some of the warnings are from there and not specific to documentation

2018-04-11 11:01 UTC, mattip commented on doc/source/docs/howto_build_docs.rst
> +module require `scipy.scpecial` to display properly. Now you are ready to
fixed

2018-04-11 11:13 UTC, mattip commented
> The HOWTO_DOCUMENT is linked to directly in many places, so needs a redirect

Some of those are actually in the `numpy/numpydoc` repo. See [pr to fix it](https://github.com/numpy/numpydoc/pull/167)

2018-04-11 11:53 UTC, pv commented
Maybe also edit doc/HOWTO_DOCUMENT.rst.txt so that it doesn't duplicate
the text in numpydoc? (Otherwise, they'll get out of sync...)

2018-04-11 14:07 UTC, mattip commented
wat? This seems to be failing on python3.6.3 linux and windows, but I cannot reproduce
```
import tokenize, ast

with tokenize.open('numpy/distutils/misc_util.py') as fid:
    txt = ast.parse(fid.read())

```
I changed  `*` to `\*` in the docstrings so they are rendered as `*` by the restructured text. It should be ignored by ast.parse

2018-04-11 14:14 UTC, mattip commented
@pv good point. They are already out of sync, comparing `doc/HOWTO_DOCUMENT.rst.txt` and (after submodule initialization) `doc/sphinxext/doc/format.rst'. I will remove the former in favor of the latter

2018-04-11 17:39 UTC, stefanv commented
I read Nathaniel's comment to mean that the HOWTO_DOCUMENT is linked to externally by a bunch of websites and projects, so we cannot remove that document without putting some kind of redirect in place.  Just want to make sure that issue has been addressed.

2018-04-11 18:27 UTC, mattip commented
ok, I added a stub document for random places like [this one](http://sphinxcontrib-napoleon.readthedocs.io/en/latest/index.html) (search for the `numpy` link on that page) that link there

2018-04-11 18:57 UTC, stefanv reviewed
This looks good to me.  I highlighted some minor typos, which may have existed before this PR.

2018-04-11 18:57 UTC, stefanv commented on doc/source/docs/howto_build_docs.rst
> +After NumPy is installed, install scipy since some of the plots in the random
Inconsistent NumPy / SciPy spelling

2018-04-11 18:57 UTC, stefanv commented on doc/source/docs/index.rst
> +Numpy's Documentation
NumPy capitalization

2018-04-11 18:57 UTC, stefanv commented on numpy/doc/glossary.py
> +       When storing a multi-byte value in memory as a sequence of bytes. the
Capitalization of t of "the"

2018-04-11 19:04 UTC, mattip commented on numpy/doc/glossary.py
> +       When storing a multi-byte value in memory as a sequence of bytes. the
s/./,/   fixed

2018-04-11 19:04 UTC, mattip commented on doc/source/docs/index.rst
> +Numpy's Documentation
fixed

2018-04-11 19:04 UTC, mattip commented on doc/source/docs/howto_build_docs.rst
> +After NumPy is installed, install scipy since some of the plots in the random
fixed

2018-04-12 11:18 UTC, mattip commented
Turns out the numpydoc submodule was pinned to `e161379f02efc4` which was 0.7, from June2017

2018-04-12 23:04 UTC, charris commented
Maybe. I'll try ye olde close and reopen trick.

2018-04-13 02:27 UTC, charris commented
I don't know it the failing tests matter. But I suppose you could close this, and make another PR from the same branch just to see what happens,

2018-04-13 14:12 UTC, mattip commented
The LGTM failure to import submodule numpydoc 0.8.0 which was released March 31 is a false positive. But merging to master would mean tests fail on master, reverting to 0.7.0 which was the version before I started touching means we loose the transition of `HOWTO_DOCUMENT.rst.txt` in numpy/master to the documentation in numpydoc, which was added as part of 0.7 -> 0.8

Maybe if we wait a week it will resolve itself?

2018-04-13 14:16 UTC, pv commented
Does the lgtm.com failure matter for master? iiuc, it only looks
whether if the number of warnings increases in PRs but doesn't care
about total number.

2018-04-14 17:16 UTC, mattip commented
@pv it would only be an issue if this is merged with the failing tests. Subsequent pull requests based off master would fail lgtm tests and we wouldn't know the root cause

2018-04-14 18:48 UTC, eric-wieser commented
Should I back out the LGTM CI?

2018-04-14 18:57 UTC, mattip commented
It seems to be just this PR, perhaps we should give LGTM.com a chance to clarify what is going on

2018-04-14 19:04 UTC, pv commented
I'd simply ignore CI failures that are the fault of the CI, so that they don't hold things back.

If it seems the CI cannot be easily fixed in reasonable time, then removing it is one option.

2018-04-15 18:44 UTC, samlanning commented
Hi Everyone,

Sorry for the problems that LGTM is having with analysing this PR, and thank you for your patience.

I've dived into it a little more, and it does seem that the problem is submodules related. More specifically, the step in our analysis that fetches all of the required git commits for all submodules is failing on the introduction of the new sub-submodule `doc/sphinxext/doc/scipy-sphinx-theme` (it's currently assuming that it already exists, and tripping up).

I've passed this on to our development team and asked them how long it would take to implement a fix for this, and will get back to you as soon as I have an estimate for that.

2018-04-15 18:54 UTC, samlanning commented
> This seems like a LGTM failure, even reverting the numpydoc submodule to 0.6 did not solve it. I am trying to work it out with them

Interesting, are you talking about https://github.com/mattip/numpy/commit/1be708ef8afd3d3d16849bc1fafef492ab53566d ? That did seem to fix the analysis as far as i can tell: https://lgtm.com/projects/g/numpy/numpy/rev/pr-88bba6b7638f9dd67caa69e362a3b0a1d4e6bbf1

2018-04-16 13:57 UTC, tibbes commented
Sorry again for the problem with LGTM. It was caused by a bug analysing pull-requests that introduce a new submodule. We are still working on a permanent fix, but we have worked around the problem for this particular submodule so the lgtm PR checks are now green for this PR.

Also, be assured that merging this PR will _not_ cause future lgtm PR analyses to fail.

2018-04-16 14:29 UTC, mattip commented
Thanks @tibbes

2018-04-16 17:59 UTC, mattip commented
@rgommers the pr still has your "changes requested" review flag

2018-04-16 18:44 UTC, rgommers approved these changes

2018-04-16 18:45 UTC, merged

2018-04-16 18:45 UTC, rgommers commented
LGTM now, merged. Thanks @mattip, all