BUG: Fix error message for resize failure
numpy/numpy pull request #12121
Opened 2018-10-09 07:45 UTC by kngwyu

Curerntly 
```python
>>> arr = np.array([1, 2, 3])
>>> arr_ref = arr
>>> arr.resize(100)
```
causes this error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function
```
But, I feel it odd to tell users to use `resize`, when `resize` fails.

2018-10-09 08:24 UTC, eric-wieser requested changes
The wording is "use the resize _function_", not "use the resize _method_". Perhaps it would be clearer to say `use the np.resize function` 

`reshape` is not a substitute for `resize`.

2018-10-09 08:38 UTC, kngwyu commented
Thanks, I changed to just propose `np.resize` or `refcheck=False`.

2018-10-11 13:27 UTC, eric-wieser commented on numpy/core/src/multiarray/shape.c
> +                    "by another array in this way.  Use the np.resize function or refcheck=False");
This is not correct - passing `refcheck = False` doesn't help if `PyArray_BASE(arr)` is set.

Either:
* remove the remark about refcheck
* Split this `if` into two ifs, and only mention refcheck in the one where `refcnt > 2` is true.

2018-10-14 03:33 UTC, kngwyu commented
Thanks, fixed by the later way.

2018-10-14 04:47 UTC, eric-wieser commented on numpy/core/src/multiarray/shape.c
>          }
As a follow up, you could move this check to be done before the other two. As you have it, there are cases where the user sees "A is not allowed, try B or C", then tries B and gets "B is not allowed, try C". If you move this check first, then the user will see "A is not allowed, try C", and fix it in one step.

2018-10-14 16:12 UTC, eric-wieser approved these changes

2018-10-14 16:13 UTC, eric-wieser commented
Would be great to add a test for that code path that codecov complains about. Creating a `weakref` to the array then trying to resize it should do the trick.

2018-10-18 05:36 UTC, kngwyu commented
Thanks. Please let me know if test location is wrong.

2018-10-18 05:48 UTC, eric-wieser approved these changes
Looks good assuming tests pass

2018-10-19 07:28 UTC, merged

2018-10-19 07:28 UTC, mattip commented
Thanks @kngwyu

2019-11-15 19:33 UTC, charris commented
Fails for wheel tests on Python 3.7. See [here.](https://travis-ci.org/numpy/numpy/jobs/612498344?utm_medium=notification&utm_source=github_status)