TST: coverage for _commonType()
numpy/numpy pull request #12201
Opened 2018-10-18 00:04 UTC by tylerjereddy

Test [uncovered path](https://codecov.io/gh/numpy/numpy/src/master/numpy/linalg/linalg.py#L148) in `np.linalg.linalg._commonType()`, where input array is of an unsupported type.

I couldn't think of more unsupported types offhand, but there may be other subclasses of `inexact` smaller than single precision that I've forgotten about.

2018-10-18 07:55 UTC, eric-wieser requested changes
It would be better to hit this code path via a public function - I suspect that calling any linalg function with a float16 argument would be enough.

2018-10-18 16:45 UTC, tylerjereddy commented
That's not true -- the first random `linalg` function I chose, `np.linalg.lingal.norm()`, worked just fine with `float16`. I'd also argue that a unit test should probe the actual function even if it is private.

If we want a supplemental *functional* test on a public function that's fine too, but we'll have to pick one that uses that code path explicitly.

2018-10-18 17:43 UTC, eric-wieser commented
`linalg.cholesky` exhibits the behavior you're after

2018-11-13 00:28 UTC, charris commented
Needs rebase and resolution of the requested changes.

2018-11-14 00:41 UTC, tylerjereddy commented
It was already revised to include both private and public function testing, but I've just deleted the private test entirely and rebased since there's not much point in starting a larger debate for such a small adjustment.

2018-11-14 00:54 UTC, charris commented
For the record, I think it is OK to test private functions when they are going to be widely used internally. If nothing else, it helps development and pins down the functionality.

2019-01-11 15:09 UTC, seberg commented
Not much point in not merging a test. Eric's comment was also addressed. It is true we do not have many unit testing in numpy, but then we have a few things that are not really tested at all ;). I don't think I mind unit tests, although I think we are OK with mostly integration tests.

Thanks Tyler!

2019-01-11 15:10 UTC, merged