DOC: Add note about arbitrary code execution to numpy.load
numpy/numpy pull request #12922
Opened 2019-02-02 18:07 UTC by adeak

Load uses pickle under the hood for object arrays, this is made
more visible in the documentation using a note.
See also gh-12759

2019-02-02 18:09 UTC, eric-wieser requested changes
Should probably be a ``warning``. I think it should come after the summary, not before it.

Phrasing is a little odd - the code execution happens whether or not the source is trusted. Perhaps try to match the warning in the python docs more closely.

2019-02-02 18:12 UTC, adeak commented
@eric-jones thanks, I was just about to add on the issue that I don't expect this to be _the_ solution, just what I had in mind, and it's easier to show than tell. I tried following the style of the deprecation note on [`numpy.matrix`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html), so the placement was at least intentional.

Could you please clarify what you meant to say by this:
> Perhaps try to match the warning in the phon done more closely.

2019-02-02 18:13 UTC, eric-wieser commented
Seems we're both typing the wrong things here. Edited.

2019-02-02 18:31 UTC, eric-wieser reviewed
To clarify, the first sentence is perfect as is.

2019-02-02 18:33 UTC, adeak commented
OK, thank you for the comments. I wasn't sure if getting very technical in the warning box would be an issue. I'll rephrase it along those lines.

2019-02-02 18:36 UTC, adeak commented
And of course, `False` is the safe one, I just didn't think it through (not having needed it in the commit originally).

2019-02-02 18:46 UTC, adeak commented
Pushed changes; still sounds a bit clumsy but I couldn't phrase it better.

Is it good form to explicitly mention this PR on the related issue, or are the automatic github links enough?

2019-02-02 19:07 UTC, eric-wieser approved these changes
Looks good now, thanks. I wonder if we also need to mention that it's simply imposible to safely to load object arrays from untrusted sources.

2019-02-02 20:59 UTC, adeak commented
I'm not sure. On the one hand emphasizing that might make the message even clearer, but on the other hand this is already obvious if one reads the docs on `allow_pickle`:
>If pickles are disallowed, loading object arrays will fail. 

As a mostly-end-user who has just learnt this safety issue of `numpy.load`: I believe that once we convey in a hard-to-miss way that `pickle` is used under the hood all the security implications instantly fall into place.

2019-02-02 21:33 UTC, eric-wieser commented
>  but on the other hand this is already obvious if one reads the docs on allow_pickle:

Sounds convincing to me.

2019-02-03 09:46 UTC, merged

2019-02-03 09:46 UTC, mattip commented
Thanks @adeak