BUG: Changed dtype comparison in _view_is_safe to be independent of name fields #13213
numpy/numpy pull request #13261
Opened 2019-04-04 14:12 UTC by lukasbrauncom

I have changed the _view_is_safe in _internal.py such that the comparison of dtypes is independent of the name field in structured arrays. This fixes issue #13213

2019-04-05 07:01 UTC, eric-wieser commented
Haven't looked at this in detail, but I think it might relate to #8514

2019-04-05 07:06 UTC, eric-wieser requested changes
Unfortunately this approach does not work for structured dtype with padding in them

2019-04-29 23:26 UTC, mattip commented
@lukasbrauncom do you wish to move forward with this? It needs tests that fail before this PR and now pass, and those tests should address the problem of padding.

2019-08-24 14:28 UTC, charris commented
@eric-wieser Is this impacted by your recent fixups?

2019-08-24 15:30 UTC, eric-wieser commented on numpy/core/_internal.py
> +    if oldtype.names or oldtype.names:
Typo, one of these should say newtype.

Should also use `.names is not None` here and above.

2020-09-08 16:33 UTC, charris commented
@eric-wieser Want to fix this up?

2022-04-06 17:18 UTC, seberg commented
We discussed this briefly, and the backport candidate label seemed unnecessary.  I am going to close this due to the fact that it stalled for a longer time and would at least need new tests.  I also expect that the machinery/fixes from gh-19346 could be interesting to generalize this more, although they are only available in C and not quite aligned with this, I think checking `view_offset == 0` may give a more generalized result than the version here.  (And staying in C is probably even nice.)

2022-04-06 17:18 UTC, closed without merging