MAINT: Added clearer clearer exception for np.diff on 0-dimensional ndarray
numpy/numpy pull request #13298
Opened 2019-04-10 15:07 UTC by navneet-nmk

Referencing #13296 

Added TypeError message in np.diff for handling 0-dimensional ndarrays.

2019-04-11 03:58 UTC, mattip commented
Please add a test that the exception type matches expectations to the `TestDiff` class in `numpy/lib/test/test_function_base.py`

2019-04-11 08:15 UTC, eric-wieser commented on numpy/lib/function_base.py
> +        raise TypeError("diff requires more than one element")
This message is very wrong
```python
arr_0d = np.array(1)
arr_1d_empty = np.array([])

assert arr_1d_empty.size == 0  # has 0 elements
np.diff(arr_1d_empty) # works fine

assert arr_0d.size > 0  # has more than 0 elements
np.diff(arr_0d) # fails
```

2019-04-11 08:15 UTC, eric-wieser requested changes
This new error message is not correct. How about just `"Input must be at least 1D"`?

2019-04-13 07:49 UTC, navneet-nmk commented
Pushed the changes as requested

2019-04-13 19:12 UTC, eric-wieser commented on numpy/lib/function_base.py
> +        raise TypeError("diff requires input that is at least one dimensional")
I think this should be a `ValueError`?

2019-04-26 16:08 UTC, mattip commented
I changed the error type and squashed the commits

2019-05-03 05:36 UTC, merged

2019-05-03 05:36 UTC, eric-wieser commented
Thanks @navneet-nmk and Matti