ENH:  better MemoryError message (#13225)
numpy/numpy pull request #13306
Opened 2019-04-11 18:55 UTC by bmakos

I am really not sure if this is the best place to place this message and if it is the good call to suppress other debug info.

2019-04-11 19:50 UTC, eric-wieser requested changes
This isn't a good place to put this message. It should go in `PyArray_New...` or something, right at the source. Search for `PyErr_NoMemory()` to find places to put it.

2019-04-13 18:06 UTC, eric-wieser commented on numpy/core/src/multiarray/ctors.c
> +            PyErr_SetObject(PyExc_MemoryError, errmsg);
Unforunately you need to check every single function call here for a `NULL` return value, else you risk producing a segfault.

This is why I've been increasingly leaning towards doing the string formatting in python.

2019-04-14 08:10 UTC, eric-wieser commented on numpy/core/src/multiarray/ctors.c
> +            if (errmsg_formatter != NULL) {
If `errmsg_formatter` returns `NULL` you should propagate it with `return NULL`

2019-04-14 08:12 UTC, eric-wieser commented on numpy/core/src/multiarray/ctors.c
> +            PyObject *err_shape = PyArray_IntTupleFromIntp(fa->nd,fa->dimensions);
Need to check if this returns `NULL` too

2019-04-14 08:15 UTC, eric-wieser commented
Another way you could handle this is via the `_exception`s route used in `type_resolution.c`, which looks like:
```
    static PyObject *exc_type = NULL;
    exc_value;

    npy_cache_import(
        "numpy.core._exceptions", "_ArrayMemoryError",
        &exc_type);
    if (exc_type == NULL) {
        return NULL;
    }

    PyObject *shape = PyArray_IntTupleFromIntp(fa->nd,fa->dimensions);
    if (shape == NULL) {
        return NULL;
    }

    /* produce an error object */
    PyObject *exc_value = PyTuple_Pack(2, shape, descr);
    Py_DECREF(shape);
    if (exc_value == NULL){
        return NULL;
    }
    PyErr_SetObject(exc_type, exc_value);
    Py_DECREF(exc_value);
    return NULL;
```

2019-04-15 08:54 UTC, bmakos commented
Who should solve the merge conflict? Should I fetch the new code and re-do my change?

2019-04-15 11:23 UTC, mattip commented
@bmakos you should solve the conflicts either by merging master into your branch or (better) rebasing off updated master, and force-pushing to your branch. If you rebase, you can squash your commits to one. Be careful when squashing, if you "reach back too far" when choosing the first commit, you will end up rewriting history of commits that are not yours.

2019-04-17 09:19 UTC, bmakos commented
I think I did the rebase and squash, but it took several attempts and re-cloning of my branch... 
`git log -p numpy/core/_exceptions.py` looks ok now, hope I did not mess up anything else.

2019-04-20 00:38 UTC, eric-wieser commented on numpy/core/_exceptions.py
> +        str(self.dtype) + "."
I don't think you should remove the trailing comma from the `shape`.

Also, consider using `.format` here, as
```python
return "Unable to allocate array with shape {} and data type {}".format(self.shape, self.dtype)
```

2019-04-24 02:17 UTC, eric-wieser approved these changes
Looks good. I'll try testing this on my windows machine and see if I can make this message appear.

2019-04-24 06:01 UTC, eric-wieser commented
Looks great:
```python
In [2]: np.zeros(10000000000000)
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-2-e424a0b4f3d7> in <module>()
----> 1 np.zeros(10000000000000)

MemoryError: Unable to allocate array with shape (10000000000000,) and data type float64
```
And just for curiosity
```
In [3]: import sys

In [4]: sys.last_value
Out[4]: numpy.core._exceptions.MemoryError((10000000000000,), dtype('float64'))
```

2019-04-24 06:34 UTC, eric-wieser commented
@charris, do you think this would be a nice addition to the release notes? Something like

```
MemoryErrors caused by allocated overly large arrays are more descriptive
---
Often the cause of a MemoryError is incorrect broadcasting resulting in a very large and incorrect shape.
The message of the error now includes this shape to help diagnose its cause.
```

2019-04-24 07:43 UTC, bmakos commented
@eric-wieser Thank you for walking me through this change, I imagine it took some patience. I struggled a bit with it, but on the way I learned a lot.

2019-04-24 13:16 UTC, charris commented
> do you think this would be a nice addition to the release notes?

Sure, there is an "Improvements" section. The notes are more likely to be  "too few" than "too many".

2019-04-25 23:16 UTC, mattip commented
Added release note. Will merge if build is OK

2019-04-26 05:50 UTC, merged

2019-04-26 05:51 UTC, mattip commented
Thanks @bmakos

2019-09-05 10:44 UTC, opprash commented
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (9681, 9681) and data type float64
how to solve this problem？

2019-09-05 14:30 UTC, bmakos commented
> numpy.core._exceptions.MemoryError: Unable to allocate array with shape (9681, 9681) and data type float64
> how to solve this problem？

It just means you ran out of memory. You could allocate a smaller array, or of a type that uses less space. You could also have more memory on your system. The solution really depends on what are you trying to do. Maybe post the code that lead to this error?

2019-09-05 14:59 UTC, seberg commented
Oh, and I thought he meant that the full module of the `MemoryError` should not show up ;). That array does not seem to be awfully big, less than one GiB. Maybe creating many.

2019-09-06 02:26 UTC, opprash commented
> > numpy.core._exceptions.MemoryError：无法分配带形状的数组（9681,9681）和数据类型float64 
> > 如何解决这个问题？
> 
> 它只是意味着你的内存不足。您可以分配较小的数组，或使用较少空间的类型。您还可以在系统上拥有更多内存。解决方案真的取决于你想做什么。也许发布导致此错误的代码？
> 
> 这个帖子也可能不是讨论这个问题的最佳场所。

Traceback (most recent call last):
  File "C:/Users/ruanlu/PycharmProjects/part_nlp/dealText/tf_idf.py", line 311, in <module>
    tfidf_mat = get_all_vector(path, stop_words)
  File "C:/Users/ruanlu/PycharmProjects/part_nlp/dealText/tf_idf.py", line 108, in get_all_vector
    idf = np.diag(idf)
  File "<__array_function__ internals>", line 6, in diag
  File "C:\Users\ruanlu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\numpy\lib\twodim_base.py", line 275, in diag
    res = zeros((n, n), v.dtype)
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (11219, 11219) and data type float64
The above is my specific error message, here I use a length array 11219, type array float idf of type float64, call np.diag (idf) to construct the error of the two-dimensional vector time report

2019-09-06 02:34 UTC, eric-wieser commented
@seberg: I think we should maybe lock this thread, its not a good place to handle this type of report.

2019-09-06 02:47 UTC, opprash commented
> @seberg: I think we should maybe lock this thread, its not a good place to handle this type of report.
Sorry, I should not discuss it in this place.

2019-09-06 14:16 UTC, seberg commented
Yeah, OK, lets lock it down.

#### If you came to this issue because saw this particular error message:

You tried to create an array and this failed because there was not enough Memory available. There are two reasons for this:
  1. The array you are creating is too large, likely by accident (inspect the shape and data type provided by the error message)
  2. Other parts of your program already use a lot of memory/RAM.

In most cases, you probably should find out what is using the memory and avoid it.