Add allow_pickle option for savez and savez_compressesd
numpy/numpy pull request #16326
Opened 2020-05-21 11:16 UTC by tinaoberoi

Reference: [Issue #13983 ](https://github.com/numpy/numpy/issues/13983)
Changes: 
- Edit function `savez `  and  ` savez_compressed `in `numpy/numpy/lib/npyio.py`
- Edit Documentation

2020-05-21 11:34 UTC, eric-wieser commented on numpy/lib/npyio.py
> +def savez(file, allow_pickle=True, *args, **kwds):
```suggestion
def savez(file, *args, allow_pickle=True, **kwds):
```

2020-05-21 11:37 UTC, eric-wieser commented
See my comments in the issue. This is unfortunately a breaking change, which makes me thing we should not do it.

2020-05-21 11:37 UTC, eric-wieser commented on numpy/lib/npyio.py
> +def savez_compressed(file, allow_pickle=True, *args, **kwds):
```suggestion
def savez_compressed(file, *args, allow_pickle=True, **kwds):
```

2020-05-21 11:39 UTC, tinaoberoi commented on numpy/lib/npyio.py
> +def savez_compressed(file, allow_pickle=True, *args, **kwds):
Done @eric-wieser

2020-05-21 11:39 UTC, tinaoberoi commented on numpy/lib/npyio.py
> +def savez(file, allow_pickle=True, *args, **kwds):
Done @eric-wieser

2020-05-21 11:43 UTC, eric-wieser commented on numpy/lib/npyio.py
> +    _savez(file, args, kwds, allow_pickle)
```suggestion
    _savez(file, args, kwds, False, allow_pickle)
```

2020-05-21 11:44 UTC, eric-wieser commented on numpy/lib/npyio.py
> +    _savez(file, args, kwds, allow_pickle)
```suggestion
    _savez(file, args, kwds, True, allow_pickle)
```

2020-05-21 11:45 UTC, eric-wieser requested changes
Just so this appears in the issue list - the PR looks like a reasonable interpretation of the issue, but I think the issue itself is a bad idea: https://github.com/numpy/numpy/issues/13983#issuecomment-632037925

2020-07-01 18:31 UTC, rossbar commented
This was discussed at a triage meeting and the consensus was that the approach motivated by the linked issue was not desirable, so I will close this for now. Thanks @tinaoberoi !

2020-07-01 18:31 UTC, closed without merging