DOC: link np.interp to SciPy's interpolation functions (#14154)
numpy/numpy pull request #16332
Opened 2020-05-21 20:02 UTC by LSchroefl

I've added a cross-link to SciPy's interpolation functions in the docstring of np.interp as suggested in #14154

2020-05-21 21:51 UTC, rossbar requested changes
Just a minor formatting change with the "See also" heading title, but otherwise LGTM.

IMO this is sufficient to address #14154.

2020-05-21 21:51 UTC, rossbar commented on numpy/lib/function_base.py
> +    See also
```suggestion
    See Also
```
per the [numpydoc standard](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard).

2020-05-22 04:34 UTC, rossbar approved these changes
LGTM, thanks @LSchroefl

2020-05-22 04:35 UTC, rossbar commented
Close/Reopen for CI

2020-05-22 05:33 UTC, merged

2020-05-22 05:34 UTC, mattip commented
Build failure unrelated. Thanks @LSchroefl. @rossbar - feel free to push the green button to merge PRs that you feel comfortable with.