BUG: Fix fit for multiple polynomial fitting
numpy/numpy pull request #16403
Opened 2020-05-27 16:18 UTC by wrzadkow

Fixes multiple polynomial fitting bug (Issue #4554 and Issue #16380). If `y.shape` is `(M, K)`, a list of `Polynomial` objects is returned, as advertised. Adds tests and updates the docstring accordingly.

2020-05-27 19:09 UTC, rossbar requested changes
Thanks @wrzadkow! If the discussion in #16380/here converges to a consensus that a list of series instances is the preferred output, the work here seems like a nice implementation of that option. 

I haven't yet gone through it in detail (particularly the tests), but did notice a few things. Hopefully this PR can help spur the discussion on what the preferred output would be for this use-case.

2020-05-27 19:09 UTC, rossbar commented on numpy/polynomial/tests/test_classes.py
> +    [q,r] = Poly.fit(x, yz, 3)
```suggestion
    q, r = Poly.fit(x, yz, 3)
```
I think a tuple for the outputs is fine here.

Also, a bit of a nit on the variable naming - I'm not sure I like `q` and `r` given their "special meaning" in linear algebra (i.e. QR factorization). Maybe `p_y` and `p_z` instead? Not a blocker, just a thought.

2020-05-27 20:46 UTC, wrzadkow commented
Many thanks, @rossbar ! I support `fit()` returning instances of `Polynomial` class, hence such implementation in this PR, but of course I'm ready to adapt this solution if the discussion converges elsewhere. 

In the meantime, I implemented all your suggestions, thanks a lot for them.

2020-05-28 17:26 UTC, rossbar commented
> I support fit() returning instances of Polynomial class, hence such implementation in this PR, but of course I'm ready to adapt the code if the discussion converges elsewhere.

I tend to agree - it would seem inconsistent for `Polynomial.fit` to return an instance in the `K=1` case, but a coefficient array in the `K > 1`. Plus the `*fit` functions from the corresponding modules (e.g. `polynomial.polyfit`) can be used to get coefficient *arrays* rather than class instances.

Either way, the current documentation is definitely out-of-sync with the implementation, so some sort of decision will have to be arrived at so we can fix this issue.

2020-06-11 20:14 UTC, rossbar commented
I'm going to close this now that #16506 is merged - thanks @wrzadkow for taking the time to put this together! I think it was helpful in framing the discussion by having a concrete example of one of the options. If the consensus in the related discussion shifts this can be revisited.

2020-06-11 20:14 UTC, closed without merging