DOC: How to verify your first NumPy bug
numpy/numpy pull request #17851
Opened 2020-11-26 10:17 UTC by a-elhag

In the last community meeting, @rgommers suggested to start with this how-to first. 

Motivation: Beginners who are looking to contribute to NumPy don't know where to start. This document is the first in a series to ease them in gently. 

Summary of how-to:
1. Setting up a virtual environment
2. Installing the appropriate version of NumPy
3. Verifying the existence of the bug
4. Uninstalling NumPy and installing the latest version + Confirm the bug has been solved

Issues:
1. Don't know how to cross reference links in Sphinx, **line 61** needs to be replaced with the appropriate link

2020-11-27 19:13 UTC, melissawm requested changes
Thanks, @a-elhag ! This looks like a great starter, I left some comments mostly about the sphinx directives. Let me know if you have questions!

2020-11-27 19:13 UTC, melissawm commented on doc/source/user/how-to-verify-bug.rst
> +bug:
```suggestion
Their claim is simple enough: the wrong dtype is returned 
if one of the inputs of the method `numpy.polymul` is a zero array. Open up a
Python terminal and type their code in and see if you can reproduce the
bug:
```

2020-11-27 19:13 UTC, melissawm commented on doc/source/user/how-to-verify-bug.rst
> +
Might be worth mentioning that if you're using venv or conda you can actually have parallel installations with different versions of NumPy.

2020-11-27 19:13 UTC, melissawm commented on doc/source/user/how-to-verify-bug.rst
> +user is experiencing the issue.
```suggestion
Go to the `NumPy GitHub issues page <https://github.com/numpy/numpy/issues>`_
and see if you can confirm the existence of any other bugs. If you can, comment
on the issue saying so. Doing this helps the NumPy developers know if more than
one user is experiencing the issue.
```

2020-11-27 19:13 UTC, melissawm commented on doc/source/user/how-to-verify-bug.rst
> +::
```suggestion
Now that the bug is confirmed, you could try and solve it by opening a PR.
Although for this specific bug, it has already been solved 
`here <https://github.com/numpy/numpy/pull/17577>`_. To confirm,
first uninstall the old version of NumPy and install the latest one::
```

(note that using two colons on the last line before the code block is enough and you don't have to add the double colon on a separate line)

2020-11-27 19:13 UTC, melissawm commented on doc/source/user/how-to-verify-bug.rst
> +.. _bug: https://github.com/numpy/numpy/issues/16354
```suggestion
This how-to will go through the process of verifying a
`bug <https://github.com/numpy/numpy/issues/16354>`_ that was submitted
on the Github issues page.
```

2020-11-27 23:22 UTC, a-elhag commented
Thanks @melissawm for the review! I've tried to address the points and the only one that is left is about **Section 2: Install the NumPy version mentioned in the bug report**. Do let me know if there are anymore changes that need to be made.

2021-02-17 17:57 UTC, melissawm commented
Hi @a-elhag ! There's some work to be done here - the CI failures are coming from the doctests on your document. Can you take a look? Thanks :)

2021-03-04 02:05 UTC, closed without merging

2021-03-04 02:34 UTC, seberg commented
It appears that this PR was incorrectly closed by github while renaming the NumPy main (previously master) branch. I suspect because the original repository was also deleted.  That seems like a github issue, but I am not sure there is a solution to it aside from opening a new PR.

Sorry about that issue, I did not review the PR. However, even if the local branches were deleted, it seems the work is still available (e.g. using `https://github.com/numpy/numpy/pull/<pull-request-number>` with the command line interface), so we can assist creating a new PR!

2022-02-07 18:01 UTC, InessaPawson commented
@a-elhag, thank you for working on this PR! It would be awesome if you could finish it. It’s such an important topic! As Sebastian said, we can help you to restore the work you submitted.

2022-02-10 11:08 UTC, rgommers commented
I suggest taking over this PR @InessaPawson and opening a new one to get this valuable content merged. Here's how I would do that:
1. Install https://cli.github.com/. This will give you the `gh` tool which helps dealing with PRs.
2. Assuming you have your repos set up so that `upstream` points to the main NumPy repo and `origin` to your own fork, do:

```bash
$ git checkout main
$ git pull  # ensure your main branch is up to date
$ gh pr checkout 17851  # this may ask you which repo to use the first time, choose numpy/numpy
$ git rebase -i HEAD^^^^

# Squash commits:
pick c103615e3 DOC: How to verify your first numpy bug
squash ae6f5b9e5 Apply suggestions from code review
squash adb0005e3 minor formatting changes
squash 225373a96 simple formating

# Use commit message:
DOC: How to verify your first numpy bug

Co-authored-by: Melissa Weber Mendonça <melissawm@gmail.com>

$ git rebase main  # This will give one conflict, resolve it and then do:
$ git add doc/source/user/howtos_index.rst
$ git rebase --continue  # now you have a new branch with a single commit on top of main
$ # address remaining content issues from review on this PR, add those as a new commit
$ git push origin howto-bug  # push changes to your own fork; after this make a new PR
```

2022-02-19 21:11 UTC, PrecisionWordcraft commented
@melissawm Shall I make review comments in this PR or should I fork and then follow the process outlined above by Ralf?

2022-02-19 21:36 UTC, PrecisionWordcraft commented on doc/source/user/how-to-verify-bug.rst
> +    '1.18.4'
This version number is the same as the one above where the bug exists. That can't be the case.

I would resolve this by noting in the running text of the doc that the version of numpy will be the latest, and that's what you should expect to see here.

2022-02-19 21:39 UTC, PrecisionWordcraft commented on doc/source/user/how-to-verify-bug.rst
> +    >>> np.polymul(a.astype(np.int64), a.astype(np.int64)).dtype
Some information as to why the returned data types aren't correct might be helpful.

2022-02-26 23:37 UTC, brandondavid commented on doc/source/user/how-to-verify-bug.rst
> +If the bug was more complex, you may need to build the NumPy version they
I would suggest _"If the bug is more complex, you may need to.."_ or _"For complex bugs, you may need to..."_