DOC: Added documentation for linter (#18423)
numpy/numpy pull request #18584
Opened 2021-03-09 17:28 UTC by ganesh-k13

### Changes:

Added documentation for lint checks as part of #18423

2021-03-09 19:54 UTC, rgommers requested changes
Thanks @ganesh-k13. Looks good, just a few small comments.

2021-03-09 19:54 UTC, rgommers commented on doc/source/dev/development_environment.rst
> +Install all dependant packages using pip::
minor: "dependent" rather than "dependant" I believe

2021-03-09 19:54 UTC, rgommers commented on doc/source/dev/development_environment.rst
> +It is advisable to run lint checks before pushing commits to remote branch
"to a remote branch"

2021-03-10 14:21 UTC, ganesh-k13 commented
Thanks for the review, Ralf. Please let me know if the style guide change is ok.

2021-03-12 18:00 UTC, rgommers approved these changes
LGTM now, thanks @ganesh-k13

2021-03-12 18:00 UTC, merged