ENH: Add SIMD operations for min and max value comparision
numpy/numpy pull request #18889
Opened 2021-05-03 06:49 UTC by HowJMay

2021-05-03 13:21 UTC, seiko2plus commented
@HowJMay, Could you please add a testing case for integer min/max?

2021-05-06 16:46 UTC, HowJMay commented
@seiko2plus Is there anything I should fix or add?

2021-05-06 19:57 UTC, seiko2plus requested changes
The current testing case only tests f32/f64, you have to add a new test case for integer max/min at the tail of the following class

https://github.com/numpy/numpy/blob/c753b23e84a5474c39999fec1f2a6d1ccd54b9a3/numpy/core/tests/test_simd.py#L158-L161

2021-05-10 07:16 UTC, seiko2plus requested changes
fix unit test cases

2021-05-10 07:16 UTC, seiko2plus commented on numpy/core/tests/test_simd.py
> +        assert simd_min == data_min
```suggestion
        data_a = self._data()
        data_b = self._data(self.nlanes)
        vdata_a, vdata_b = self.load(data_a), self.load(data_b)

        data_max = [max(a, b) for a, b in zip(data_a, data_b)]
        simd_max = self.max(vdata_a, vdata_b)
        assert simd_max == data_max

        data_min = [min(a, b) for a, b in zip(data_a, data_b)]
        simd_min = self.min(vdata_a, vdata_b)
        assert simd_min == data_min
```

2021-05-10 07:43 UTC, seiko2plus approved these changes
LGTM, Thank you.

2021-05-10 10:04 UTC, HowJMay commented
> LGTM, Thank you.

Thank you so much for helping

2021-05-10 18:24 UTC, merged

2021-05-10 18:24 UTC, charris commented
Thanks @HowJMay .