Clarify docs in np.random that inform that one should use a Generator
numpy/numpy pull request #18966
Opened 2021-05-09 17:00 UTC by kubekmonika

I changed the descriptions so that now:
* they say about `Generator` instance and not `default_rng()` instance, as the later is only a class constructor,
* under See Also section one can find a link to the recommended `Generator` constructor.

Closes #17140

2021-05-09 18:49 UTC, rkern requested changes
You can remove all of the lines referring to `default_rng` in the `See Also` sections. That's not particularly germane to each of these methods

2021-05-09 18:49 UTC, rkern commented on numpy/random/mtrand.pyx
> +        Generator.default_rng: Recommended constructor for `Generator`.
This is not needed for these methods.

2021-05-09 19:23 UTC, rkern commented
The original bug report #17140 was more about the fact that the referred-to method was not a clickable link (and secondarily that it ought not to refer to the non-existent "`default_rng` instances"). You'll have to use single-backticks to get the links. I would probably write those sentences like so:

```
            New code should use the `Generator.random` method instead; please
            see the :ref:`random-quick-start`.
```

I see in that issue that it was recommended that `default_rng` be added to the `See Also` list, but I think that is not a good idea. The reference to the `Quick Start` material in the note is more useful.

In order to make the methods in the `See Also` list clickable, there needs to be a space before the `:`. The ReST parser treats those two cases differently. That would be helpful to close #17140 fully.

2021-05-09 21:37 UTC, rkern commented
Actually, the full syntax for the `note` should look like this, in order to fix the links:

```
            New code should use the :meth:`~numpy.random.Generator.random`
            method of a :class:`~numpy.random.Generator` instance instead;
            please see the :ref:`random-quick-start`.
```

The default scoping for these method docstrings look up only _under_ `RandomState` rather than up to `numpy.random`, unfortunately. So we need to use the fully-qualified `numpy.random.Generator` in order to locate the correct referent. Using the `~` makes the generated HTML only use the part after the last `.` as the link text, though, so this will read as "use the `random` method of a `Generator` instance" with the correct links.

Similarly, the `See Also` section needs fully-qualified references in addition to the spaces before and after the colon:

```
        See Also
        --------
        numpy.random.Generator.random : which should be used for new code.
```

2022-02-09 14:21 UTC, melissawm commented
Hello, @kubekmonika - are you interested in picking up this PR again? If you need help with it feel free to ping me. Thanks!

2022-07-06 00:58 UTC, charris commented
This looks pretty straight forward, a few fixes should make it ready to go. The conflicts are due to `default_rng` being removed from the `See Also` section and should be easy to fix.

2022-09-17 05:55 UTC, bsipocz commented
I've rebased this PR to resolve the conflicts and finished addressing the review items in #22304, closing this one now (the referenced, original issue has been addressed in the meantime and is now closed, too)


Thank you @kubekmonika for your contribution, your code changes have been also moved to the other PR.

2022-09-17 05:55 UTC, closed without merging