DOC: add example showing how to convert POSIX timestamps to datetime64
numpy/numpy pull request #18984
Opened 2021-05-10 16:11 UTC by jonathangjertsen

2021-05-10 16:21 UTC, jonathangjertsen commented
I accidentally committed my text editor's removal of trailing whitespace. Let me know if I should amend the commit to undo it

2021-05-24 21:02 UTC, melissawm requested changes
Hi @jonathangjertsen - thanks for that! As you can see in the generated [CircleCI artifact](https://19788-908607-gh.circle-artifacts.com/0/doc/build/html/reference/arrays.datetime.html), your example doesn't show up - you are missing a space before the word "Example". Otherwise, looks good to me!

It's a good idea to [build the docs locally](https://numpy.org/devdocs/docs/howto_build_docs.html) when you do a change and check that it all works, let me know if you need help with that.

2021-05-24 21:02 UTC, melissawm commented on doc/source/reference/arrays.datetime.rst
> +.. admonition::Example
```suggestion
.. admonition:: Example
```

2021-05-24 21:19 UTC, jonathangjertsen commented
> It's a good idea to [build the docs locally](https://numpy.org/devdocs/docs/howto_build_docs.html) when you do a change and check that it all works, let me know if you need help with that.

Thanks, I'll make sure to do that next time

2021-10-01 17:54 UTC, melissawm approved these changes

2021-10-01 17:55 UTC, merged

2021-10-01 17:55 UTC, melissawm commented
Thanks, @jonathangjertsen !