ENH: Implement SIMD for ceiling
numpy/numpy pull request #19022
Opened 2021-05-16 14:56 UTC by HowJMay

2021-05-30 09:55 UTC, HowJMay commented
Sorry @seiko2plus I have some problem reading the error message in [CI](https://github.com/numpy/numpy/pull/19022/checks?check_run_id=2704066507)

When I saw `Test_SIMD_FP_128_baseline_f32`, I am not sure which architecture it is using. Is it `SSE`?

The other thing is there is no direct way to truncate a double precision floating number, so I choose to use a pure c implementation. Is it ok?

2021-08-10 05:07 UTC, seiko2plus reviewed
Sorry for the delayed response, the baseline features are configured through build option `--cpu-baseline`, the default setting on x86_64 is equivalent to `SSE SSE2 SSE3`.

The current CI error is related to the emulated version of `npyv_ceil_f32`, see my comment blow for more clarification.

2021-08-24 03:17 UTC, HowJMay commented on numpy/core/src/common/simd/neon/math.h
> +    #define npyv_ceil_f32 vrndpq_f32
thanks!

2021-08-24 03:17 UTC, HowJMay commented on numpy/core/tests/test_simd.py
> +        assert ceil == data_ceil
thanks!

2021-08-24 03:17 UTC, HowJMay commented on numpy/core/src/common/simd/sse/math.h
> +        return _mm_set_pd(ceil(_a[1]), ceil(_a[0]));
thank you for this information!

2021-08-24 03:17 UTC, HowJMay commented on numpy/core/src/common/simd/sse/math.h
> +    }
thank you for explaining

2021-08-26 13:00 UTC, seiko2plus requested changes

2021-10-05 20:29 UTC, seiko2plus requested changes
Just one case left, the ceil implementation of Armv7/Neon should respect the special cases, and signed zero similar to other extensions.

2021-10-05 20:29 UTC, seiko2plus commented on numpy/core/src/common/simd/neon/math.h
> +   }
```suggestion
NPY_FINLINE npyv_f32 npyv_ceil_f32(npyv_f32 a)
    {
        const npyv_s32 szero = vreinterpretq_s32_f32(vdupq_n_f32(-0.0f));
        const npyv_u32 one = vreinterpretq_u32_f32(vdupq_n_f32(1.0f));
        const npyv_s32 max_int = vdupq_n_s32(0x7fffffff);
        /**
         * On armv7, vcvtq.f32 handles special cases as follows:
         *  NaN return 0
         * +inf or +outrange return 0x80000000(-0.0f)
         * -inf or -outrange return 0x7fffffff(nan)
         */
        npyv_s32 roundi = vcvtq_s32_f32(a);
        npyv_f32 round = vcvtq_f32_s32(roundi);
        npyv_f32 ceil = vaddq_f32(round, vreinterpretq_f32_u32(
            vandq_u32(vcltq_f32(round, a), one))
        ); 
        // respect signed zero, e.g. -0.5 -> -0.0
        npyv_f32 rzero = vreinterpretq_f32_s32(vorrq_s32(
            vreinterpretq_s32_f32(ceil),
            vandq_s32(vreinterpretq_s32_f32(a), szero)
        ));
        // if nan or overflow return a
        npyv_u32 nnan = npyv_notnan_f32(a);
        npyv_u32 overflow = vorrq_u32(
            vceqq_s32(roundi, szero), vceqq_s32(roundi, max_int)
        );
        return vbslq_f32(vbicq_u32(nnan, overflow), rzero, a);
    }

```

Similar to the other architectures, ceil_f32 should respect special cases and signed zero.
My suggestion here is similar to the SSE version except for handling finite and outranges due to the nature of `vcvtq_s32_f32`.

Note that CI doesn't cover armv7/neon neither aarch32/ASIMD so I had to test it on my local machine and it seems good to me.

2021-10-05 20:32 UTC, seiko2plus commented on numpy/core/src/common/simd/avx512/math.h
> +NPYV_IMPL_AVX512_FROM_AVX2_PD_1ARG(npyv_ceil_f64, _mm256_ceil_pd)
no problem, let's keep them then. thank you

2021-11-01 17:21 UTC, seiko2plus commented on numpy/core/src/common/simd/neon/math.h
> +   }
update: we have now a CI/workflow for testing universal intrinsics on armv7/aarch32.

2021-11-01 17:26 UTC, seiko2plus approved these changes
Thank you Yang Hau. We still need to add intrinsics for `floor, trunc, rint` so we can get ride of the following raw x86 SIMD.

https://github.com/numpy/numpy/blob/fa397e9d9a821a178ad620b28bb334b800d2c93d/numpy/core/src/umath/simd.inc.src#L1400-L1411

2021-11-02 03:58 UTC, HowJMay commented
> Thank you Yang Hau. We still need to add intrinsics for `floor, trunc, rint` so we can get ride of the following raw x86 SIMD.
> 
> https://github.com/numpy/numpy/blob/fa397e9d9a821a178ad620b28bb334b800d2c93d/numpy/core/src/umath/simd.inc.src#L1400-L1411

Let me work on them

2021-11-03 02:26 UTC, HowJMay commented
I will work on the following intrinsics once this PR being merge!

2021-11-03 08:26 UTC, HowJMay commented
Hi @seiko2plus, sorry for disturbing. I just found some inconsistency in the implementation of NEON's one and SSE's one. When encountering `NAN`, `±INF`, I think the correct behavior is returning the input argument `a`? If so, I should add the protection on other architectures. One thing I am curious is, on some architectures, we simply implement `ceil` with macro, then, should we add protection to these functions?

2021-11-03 14:05 UTC, seiko2plus commented
> I will work on the following intrinsics once this PR being merge!

let's wait +1 day more before merging this pr, to give chance to other contributors to review it.

> When encountering NAN, ±INF, I think the correct behavior is returning the input argument a?

I'm not sure exactly what you mean, but this patch already handles the following for all extensions:
- If arg is ±∞, it is returned unmodified
- If arg is ±0, it is returned, unmodified
- If arg is NaN, NaN is returned

In the case of `FE_INEXACT` which I think is what you mean. Yes, we return the arg(`a`) for the emulated intrinsics of `NEON` and `SSE<4.1`when encountering `overflow` without raising `FE_INEXACT exception` which can be acceptable.

>  If so, I should add the protection on other architectures.

no, non-emulated intrinsics(native) support IEEE floating-point arithmetic (IEC 60559), and correctly handle `FE_INEXACT`.

2021-11-03 14:14 UTC, seiko2plus commented
@mattip, ping

2021-11-03 16:48 UTC, HowJMay commented
Hi @seiko2plus 
What I worry is we are not handling `NAN` case under `SSE<4.1`. Maybe I miss something?

2021-11-03 16:55 UTC, seiko2plus commented
Hi @HowJMay, Yes, it handles both nan/inf cases please check my comment https://github.com/numpy/numpy/pull/19022#discussion_r685587127

2021-11-03 16:57 UTC, seiko2plus commented
> What I worry is we are not handling NAN case under SSE<4.1.

Why being worry? we already have test cases for it.

2021-11-03 17:02 UTC, HowJMay commented
> > What I worry is we are not handling NAN case under SSE<4.1.
> 
> Why being worry? we already have test cases for it.

That's true haha 😆😆😆😆

2021-11-03 18:03 UTC, mattip commented
Is there a benchmark run that shows the improvement? How much does this inflate the `_multiarray_umath` shared object?

2021-11-03 19:53 UTC, seiko2plus commented
@mattip, This pr only add universal intrinsics for ceil, so it can be used to replace the current existence raw SIMD in:

https://github.com/numpy/numpy/blob/fa397e9d9a821a178ad620b28bb334b800d2c93d/numpy/core/src/umath/simd.inc.src#L1400-L1411

2021-11-03 20:16 UTC, merged

2021-11-03 20:16 UTC, mattip commented
Thanks @HowJMay and for the review @seiko2plus