BUG: genfromtxt should return empty array when file is empty
numpy/numpy pull request #20107
Opened 2021-10-13 01:48 UTC by matthieuheitz

72ab385 says genfromtxt returns empty array for empty input file instead of an error. 
This should work regardless of the parameters we pass to np.genfromtxt() 

But currently it doesn't work when `names=True`:
```
data = io.StringIO()
test = np.genfromtxt(data, names=True)
```
This produces the warning, and instead of returning an empty array, we get an IndexError on the line:
	`fval = first_values[0].strip()`

To address this, an empty array must be returned directly after the warning.

2021-10-13 14:47 UTC, BvB93 reviewed
``` diff
-         if names is True:
+         if names is True and len(first_values) > 0:
```

I'd suggest moving the check down a little bit to [here](https://github.com/numpy/numpy/blob/6c38e056d702202167e6de6ab6e2aa02cc26d850/numpy/lib/npyio.py#L1855).

There is _a lot_ going on in the `genfromtxt` function, and, quite frankly, I'm a bit concerned that the early return you're proposing could have unexpected side effects when dealing with certain argument-combinations.

Also, could you add a new test for these types of empty files to [numpy/lib/tests/test_io.py](https://github.com/numpy/numpy/blob/main/numpy/lib/tests/test_io.py)?

2021-12-02 05:25 UTC, scratchmex requested changes
I think with this should be fine. Also, please add a test :D

2021-12-02 05:25 UTC, scratchmex commented on numpy/lib/npyio.py
>          if names is True:
```suggestion
        if names is True and first_values:
```

2021-12-02 05:25 UTC, scratchmex commented on numpy/lib/npyio.py
> +            return np.array([])
as suggested, let's avoid returning early

2022-09-26 12:16 UTC, seberg commented
Are we actually sure about the change?  I am not.  With `names=True` the user asks NumPy to infer names from the file.  That means NumPy should be able to actually infer them!

NumPy supports it just fine if the file contains no *data*, it just complains when it cannot even infer the names.

I lean towards changing the documentation, if that is even necessary here.

2022-12-08 12:36 UTC, seberg commented
Just stumbled on this again, I still don't really agree with the proposed API change.

Note, if anyone disagrees even a bit and wants to argue for the change don't hesitate to comment and I will reopen.  As is, I think the PR cannot not move unfortunately, and thus I am closing it.

Thanks for taking the trouble to look into it and work on the PR!

2022-12-08 12:36 UTC, closed without merging