BUG: Raise different type of errors
numpy/numpy pull request #20389
Opened 2021-11-16 23:13 UTC by andrekwr

Hello,

I added the errors messages as proposed by @WarrenWeckesser in #20329.

2021-11-17 21:25 UTC, mattip commented
Please check your indentation

2021-11-18 08:18 UTC, mattip commented
The conda build failure is expected.

2021-11-18 12:56 UTC, WarrenWeckesser commented
Thanks @andrekwr!

Some of those `try/except` statements aren't doing anything useful, so I think the changes can be simplified quite a bit.

The reason for catching and reraising the `TyepError` exception in this block of code is to provide the user with a more informative error message about the arguments given to `genfromtxt`.   If we remove the `try/except` statements completely, the code (with an editorial comment added) looks like:
```python
    if isinstance(fname, os_PathLike):
        fname = os_fspath(fname)
    if isinstance(fname, str):
        fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
        fid_ctx = contextlib.closing(fid)
    else:
        # If here, we expect fname to be a sequence or iterator of strings.
        fid = fname
        fid_ctx = contextlib.nullcontext(fid)
    fhd = iter(fid)
```
For many cases, bad input to this code will result in an exception that gives a reasonable error message to the user without having to reraise an exception.  Some examples:

* The file does not exist:
  ```
  In [23]: np.genfromtxt('nonesuch.dat')
  ---------------------------------------------------------------------------
  FileNotFoundError                         Traceback (most recent call last)
  <ipython-input-23-05210d43ec13> in <module>
  ----> 1 np.genfromtxt('nonesuch.dat')
  ... snip ...
  FileNotFoundError: nonesuch.dat not found.
  ```
* An encoding parameter with the wrong type:
  ```
  In [25]: np.genfromtxt('data.txt', encoding=int)
  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  <ipython-input-25-15f3293acb50> in <module>
  ----> 1 np.genfromtxt('data.txt', encoding=int)
  ... snip ...
  TypeError: open() argument 'encoding' must be str or None, not type
  ```
The error messages that are not very helpful occur when the first argument is not a string or a path, and also not an iterator, such as an integer or `None`:
 ```
In [26]: np.genfromtxt(12345)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-726bcd824d92> in <module>
----> 1 np.genfromtxt(12345)

~/mc39numpy/lib/python3.9/site-packages/numpy/lib/npyio.py in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding, like)
   1818         fid = fname
   1819         fid_ctx = contextlib.nullcontext(fid)
-> 1820     fhd = iter(fid)
   1821 
   1822     with fid_ctx:

TypeError: 'int' object is not iterable

In [27]: np.genfromtxt(None)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-37c00eace4cb> in <module>
----> 1 np.genfromtxt(None)

~/mc39numpy/lib/python3.9/site-packages/numpy/lib/npyio.py in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding, like)
   1818         fid = fname
   1819         fid_ctx = contextlib.nullcontext(fid)
-> 1820     fhd = iter(fid)
   1821 
   1822     with fid_ctx:

TypeError: 'NoneType' object is not iterable
```
So I think the only code that needs to be wrapped in a `try/except` statement is the one line `fhd = iter(fid)`. The updated code becomes:

```python
    if isinstance(fname, os_PathLike):
        fname = os_fspath(fname)
    if isinstance(fname, str):
        fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
        fid_ctx = contextlib.closing(fid)
    else:
        # If here, we expect fname to be a sequence or iterator of strings.
        fid = fname
        fid_ctx = contextlib.nullcontext(fid)
    try:
        fhd = iter(fid)
    except TypeError as e:
        raise TypeError(
            "fname must be a string, a filehandle, a sequence of strings,\n"
            f"or an iterator of strings. Got {type(fname)} instead."
        ) from e
```
Note that I did some copy-editing in the error message of the reraised `TypeError`.
Then `np.genfromtxt(123)` gives the more informative error message:
```
In [2]: np.genfromtxt(123)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/mc39numpy/lib/python3.9/site-packages/numpy/lib/npyio.py in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding, like)
   1819     try:
-> 1820         fhd = iter(fid)
   1821     except TypeError as e:

TypeError: 'int' object is not iterable

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-2-096a3b4ec972> in <module>
----> 1 np.genfromtxt(123)

~/mc39numpy/lib/python3.9/site-packages/numpy/lib/npyio.py in genfromtxt(fname, dtype, comments, delimiter, skip_header, skip_footer, converters, missing_values, filling_values, usecols, names, excludelist, deletechars, replace_space, autostrip, case_sensitive, defaultfmt, unpack, usemask, loose, invalid_raise, max_rows, encoding, like)
   1820         fhd = iter(fid)
   1821     except TypeError as e:
-> 1822         raise TypeError(
   1823             "fname must be a string, a filehandle, a sequence of strings,\n"
   1824             f"or an iterator of strings. Got {type(fname)} instead."

TypeError: fname must be a string, a filehandle, a sequence of strings,
or an iterator of strings. Got <class 'int'> instead.
```

We should add a unit test for this behavior.  The tests for `genfromtxt` are in the class [`TestFromTxt`](https://github.com/numpy/numpy/blob/d4243a381778109ba2522ed7d155e1338e4ca6de/numpy/lib/tests/test_io.py#L1269) in the file [`numpy/lib/tests/test_io.py`](https://github.com/numpy/numpy/blob/d4243a381778109ba2522ed7d155e1338e4ca6de/numpy/lib/tests/test_io.py).  We can create a unit test for the error handling by adding a method such as the following to `TestFromTxt`:

```
    def test_bad_fname(self):
        with pytest.raises(TypeError, match='fname must be a string,'):
            np.genfromtxt(123)
```

2021-11-18 14:16 UTC, WarrenWeckesser requested changes
(Github requires a comment here before I can submit the review with "Request changes" clicked. The requested changes are in my previous comment.)

2021-11-23 20:00 UTC, andrekwr commented
Hey @WarrenWeckesser , sorry for the delay.
I did those try/except to ensure that everything was being correctly handled, but i think you are write. I just commited the changes you requested.

2021-12-03 23:57 UTC, WarrenWeckesser approved these changes
Thanks @andrekwr.

There are a few whitespace issues that I'll fix, and then I'll merge.

2021-12-03 23:57 UTC, WarrenWeckesser commented on numpy/lib/npyio.py
> +
```suggestion

```

2021-12-03 23:57 UTC, WarrenWeckesser commented on numpy/lib/npyio.py
> +
```suggestion

```

2021-12-03 23:57 UTC, WarrenWeckesser commented on numpy/lib/tests/test_io.py
> +
```suggestion
```

2021-12-04 00:11 UTC, merged