ENH: Extending CPU feature detection framework to support IBM Z SIMD
numpy/numpy pull request #20552
Opened 2021-12-09 11:45 UTC by pradghos

We would like to extend CPU feature detection infrastructure for IBM Z CPU features. 
Eventually It will help to add and enable Z specific SIMD builtins and instructions.

As part of the PR, we have extended `ccompiler_opt.py`, `npy_cpu_features.c.src`, 
`npy_cpu_features.h`, other files for Z CPU feature detection and added test files for 
`VX/VXE/VXE2` in `distutils/checks`.

cc @edelsohn @Andreas-Krebbel @potula-chandra @ajaypvictor

2021-12-09 13:33 UTC, edelsohn commented
@seiko2plus Sayed, what's your progress?

2021-12-11 15:52 UTC, seiko2plus requested changes
Hello @pradghos, along with the following suggestions we still need to add to test runtime detection similar to:
https://github.com/numpy/numpy/blob/93301a53aad8ddda15a25415e9af8f574cd758a8/numpy/core/tests/test_cpu_features.py#L140-L147.

2021-12-11 15:52 UTC, seiko2plus commented on numpy/core/src/common/npy_cpu_features.c.src
> +#elif defined(NPY_CPU_S390) || defined(__s390x__)
```suggestion
#elif defined(__s390x__)
```
it supposed be enabled only for zarch

2021-12-11 16:05 UTC, seiko2plus commented
@edelsohn,
> @seiko2plus Sayed, what's your progress?

we have several SIMD kernels now written by universal intrinsics, and more coming. I was working on s390x implementation but I pause it in favor of replacing/implementing more kernels to universal intrinsics first.

2021-12-13 21:02 UTC, pradghos commented
Hi @seiko2plus,  I have incorporated the review comments now, Thank you very much for the review !

2021-12-14 15:22 UTC, seiko2plus approved these changes
Thank you Pradipta, I have updated the document of build options, and added extra tests for s390x to guarantee that IBM Z features don't get affected by future changes to our infrastructure.

2021-12-14 16:16 UTC, merged

2021-12-14 16:17 UTC, mattip commented
Thanks @pradghos, @seiko2plus

2021-12-15 06:05 UTC, potula-chandra commented
Excellent thank you @pradghos, @seiko2plus  and  @mattip

2021-12-15 14:37 UTC, seiko2plus commented on numpy/distutils/tests/test_ccompiler_opt.py
> +            s390="-mzvector -march=arch12"
what a typo see #20588

2022-01-04 17:19 UTC, InessaPawson commented
Hi-five on merging your first pull request to NumPy, @pradghos! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute/. 
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion