MAINT: f2py: don't  generate code that triggers `-Wsometimes-uninitialized`
numpy/numpy pull request #20940
Opened 2022-01-29 20:44 UTC by rgommers

Warnings all look like:

```
scipy/linalg/_flapackmodule.c:2200:9: warning: variable 'return_value' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
    if (capi_j>capi_i)
        ^~~~~~~~~~~~~
scipy/linalg/_flapackmodule.c:2217:12: note: uninitialized use occurs here
    return return_value;
           ^~~~~~~~~~~~
scipy/linalg/_flapackmodule.c:2200:5: note: remove the 'if' if its condition is always true
    if (capi_j>capi_i)
    ^~~~~~~~~~~~~~~~~~
scipy/linalg/_flapackmodule.c:2099:21: note: initialize the variable 'return_value' to silence this warning
    int return_value;
                    ^
                     = 0
```

2022-01-29 21:50 UTC, charris commented
I take it you would like this backported?

2022-01-29 21:52 UTC, charris commented
Is that the correct return value in those cases?

2022-01-29 21:59 UTC, rgommers commented
> Is that the correct return value in those cases?

Not sure, it may be that something else is missing. That code is pretty much unreadable.

2022-01-29 22:00 UTC, rgommers commented
Figure `= 0` is better than uninitialized use

2022-01-29 22:03 UTC, charris commented
> Not sure, it may be that something else is missing.

I'll leave it to 1.22.3 then. I want to get the initial 1.22.x problems fixed up as soon as possible so we can deal with the more obscure ones.

2022-01-30 03:15 UTC, charris commented
@HaoZeke @pearu Thoughts?

2022-01-30 03:22 UTC, HaoZeke commented
Since this code is generated it would be better to initialize it within the `if` condition instead of unconditionally. The warning suggests that F2PY codegen can be improved and initializing it to zero would prematurely silence warnings when better fixes might make sense.

Basically I would prefer to fix the return statement generation than the initialization.

2022-01-31 09:33 UTC, pearu commented
Background: the referenced code corresponds to call-back functions that a Fortran function uses to call Python functions. Normally, a non-void call-back function is expected to return a value, that is, the user-provided Python function ought to return a numeric value. However, if it returns `None` (as specified by a user), then `(capi_j > capi_i)` is `false` and the value of `return_value` is undefined. Since this undefined behavior is under the user's control, f2py allows it, although it will be silent. Initializing `return_value` to `0` (for the sake of silencing the compiler) makes this undefined behavior even more silent.

To fix this issue, we have the following objectives:
1. As a primary one, enforce users to write well-defined code (non-void call-backs should always return a value)
2. Silence the compiler as a secondary objective (initialize `return_value`)
3. The change should be non-BC-breaking (cannot raise an exception when a user callback does not provide a return value, for instance)

I suggest the following solution:
1. When a non-void user callback does not provide a return value, trigger a warning. The corresponding code should be inserted here as `else` block to `if (capi_j > capi_i)`: https://github.com/numpy/numpy/blob/fb0cdc331e0f559e2237fa2e077a4e712f1fee36/numpy/f2py/cb_rules.py#L235
2. Initialize `return_value`. This will be trickier as the return type can be any scalar, including `complex`. The initialization can be carried out in the same `else` block as in 1.

2022-01-31 10:05 UTC, pearu requested changes
Handle complex return value case and trigger a warning if user-provided cb function does return a value.

2022-01-31 10:05 UTC, pearu commented on numpy/f2py/cb_rules.py
>                        {debugcapi:
```suggestion
                      fprintf(stderr,\"callback #name# does not provide return value\\n\");
                      {debugcapi:
```

2022-01-31 10:08 UTC, pearu commented on numpy/f2py/cb_rules.py
>                        {debugcapi:
The suggestion requires better formatting (flake8 will likely fail here) but I hope the intention of the suggestion is clear.

2022-01-31 10:17 UTC, rgommers commented
Thanks @pearu. Do you just want to push to this PR? I'm happy for you to take it over. My change is just a minimal "make annoying warnings go away", but I have little desire to make further changes.

2022-01-31 10:32 UTC, pearu commented
@rgommers how about this: I'll push changes to your branch and make sure that numpy CI is green, and you'll take care of testing the scipy part?

2022-01-31 10:36 UTC, rgommers commented
Sure, that sounds good!

2022-01-31 13:51 UTC, pearu approved these changes
@rgommers please review.

2022-02-01 17:25 UTC, rgommers reviewed
This is nice, SciPy build is much happier and the generated code is now readable which is useful too. Thanks @pearu!

2022-02-01 17:26 UTC, merged