BUG: Fix negative bounds for F2PY
numpy/numpy pull request #21256
Opened 2022-03-27 17:52 UTC by HaoZeke

Closes #20853.

However, there are some implementation notes which are important.

This PR changes the behaviour of the **python caller**, which is now responsible for being the right size. That is:

```fortran
subroutine foo(is_,ie_,arr)
 implicit none
 integer :: is_,ie_ 
 real*8 :: arr(is_:ie_)
end
```

After compiling `f2py -m blah blah.f90`, this can be called with:

```python
import numpy as np
import blah
xlow = -6
xhigh = 4
xvec = np.arange(12)
def ubound(xl, xh):
  return abs(xl) + abs(xh) + 1
blah.foo(is_ = xlow, ie_ xhigh,
         arr = xvec[:ubound(xlow, xhigh)) 
```

Essentially, the caller is now responsible in this scenario for ensuring that the bounds are correct.

2022-03-27 18:10 UTC, charris commented
Does this work with SciPy?

2022-03-27 19:56 UTC, HaoZeke commented
> Does this work with SciPy?

Yup, in so far as there are no examples of the original issue showing up in SciPy and the change in behavior is only triggered for the case when:
- The dimensions of an array are defined by other input variables
  - Essentially for an `array` of size `xlow:xhigh` which are also variables

I also ran `runtests.py` cleanly (on `scipy` master). @melissawm would be the best person to confirm that SciPy works though :)

2022-03-29 17:06 UTC, pearu requested changes
Thanks, @HaoZeke for this!

I have a suggestion for detecting the cyclic dependence using `coeffs_and_deps` data only that targets the original issue more precisly.

2022-03-29 17:21 UTC, HaoZeke commented on numpy/f2py/crackfortran.py
>                              if solver is not None:
Yup, but computing `cyclic_dims` immediately after checking `isarray` broke all the threading tests

2022-03-29 17:43 UTC, HaoZeke commented on numpy/f2py/crackfortran.py
>                              if solver is not None:
Neat, this seems much cleaner, thanks!

2022-03-29 19:44 UTC, pearu requested changes
I have a few minor nits but otherwise looks good!

2022-03-29 19:44 UTC, pearu commented on numpy/f2py/tests/test_regression.py
> +            return abs(xl) + abs(xh) + 1
Nit: for exact upper bound, use
```suggestion
            return xh - xl + 1
```
Notice that when using all negative bounds, say,
```
xlow = -8
xhigh = -2
```
then the abs-approach gives a wrong result for the upper bound.

2022-03-29 19:44 UTC, pearu commented on numpy/f2py/crackfortran.py
> +import itertools
```suggestion
```
?

2022-03-29 20:37 UTC, pearu approved these changes
LGTM!

2022-03-31 14:51 UTC, melissawm commented
Let's put this in - thanks @HaoZeke !

2022-03-31 14:51 UTC, merged