DOC: clarify loadtxt input cols requirement
numpy/numpy pull request #21861
Opened 2022-06-28 00:29 UTC by pranabdas

As discussed in https://github.com/numpy/numpy/pull/21854#issuecomment-1167756869. 

@seberg instead of removing the sentence, I tried to provide more clarification.

2022-06-28 02:47 UTC, seberg commented
Thanks!  It would be nice to have a paragraph of text there.  The reason why I suggested to remove it was that it seems like too much detail for the first thing you read about `np.loadtxt`.

Maybe someone from the docs team has a good idea.  I don't mind the information here, but would prefer leading with more generic information (for example that loadtxt is useful to parse a CSV file given the correct parameters/delimiter).

2022-06-28 03:06 UTC, WarrenWeckesser commented
How about moving that paragraph to the Notes section?

2022-06-28 07:49 UTC, rossbar commented
I agree with @WarrenWeckesser 's suggestion - the Notes section seems like the correct place for this amount of detail. In principle an example could be added, but it feels strange to *recommend* this practice to users.

2022-07-02 03:54 UTC, WarrenWeckesser requested changes
Thank @pranabdas, looks good.  I requested a slight tweak for the formatting of the text.

The addition of the example is great.

2022-07-02 03:54 UTC, WarrenWeckesser commented on numpy/lib/npyio.py
> +      in all rows) can be read by specifying the columns via `usecols`.
Nitpick: these two sections don't need to be bulleted.  Regular paragraphs with a blank line between them should be fine.  Also, change `n-columns` to `n columns`.
```suggestion
    This function aims to be a fast reader for simply formatted files.  The
    `genfromtxt` function provides more sophisticated handling of, e.g.,
    lines with missing values.

    Each row in the input text file must have the same number of values to be
    able to read all values. If all rows do not have same number of values, a
    subset of up to n columns (where n is the least number of values present
    in all rows) can be read by specifying the columns via `usecols`.
```

2022-07-02 04:04 UTC, merged

2022-07-02 04:06 UTC, WarrenWeckesser commented
My suggested changes were trivial, so I pushed them myself and merged.  Thanks @pranabdas!