Added priority in bug-report issue-template
numpy/numpy pull request #21965
Opened 2022-07-11 10:41 UTC by ZicsX

Added the following to the “Bug report” issue template:
- Dropdown to select the priority
- Textarea for Mentioning the Significance of the issue.

**Priority**:
- P1 (Critical)
- P2 (High)
- P3 (Medium)
- P4 (Low)
- P5 (Trivial)

**Significance of the issue**:
- textarea to mention the significance of the issue.

Justification:
Mentioning the priority of an issue will help the core developers and triage team to better understand and manage open issues.
We can also set up GitHub Bot to automatically assign a label to the issue based on the priority.

This Pull request closes #21919.

2022-07-11 12:00 UTC, melissawm commented
Hi @ZicsX ! I'm not sure we should keep the priority dropdown - I think just the text area with an explanation of how this issue impacts the person reporting is enough for the maintainers to decide on priorities. 

@InessaPawson what do you think?

2022-07-11 16:56 UTC, InessaPawson requested changes
@ZicsX Thank you for taking initiative to fix this issue! I agree with @melissawm, we shouldn't introduce levels of prioritization to the issue template.

2022-07-11 16:56 UTC, InessaPawson commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +      Please explain how this issue negatively affects your work or why it should be prioritized.
```suggestion
      Please explain how this issue affects your work or why it should be prioritized.
```

2022-07-11 16:56 UTC, InessaPawson commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +    label: "Significance of the issue:"
```suggestion
    label: "Context for the issue:"
```

2022-07-14 12:49 UTC, ZicsX commented on .github/ISSUE_TEMPLATE/bug-report.yml
> +    required: true
Sure!

2022-08-07 03:55 UTC, InessaPawson approved these changes
Looks great! Thank you for your help, @ZicsX!

2022-08-07 18:32 UTC, merged

2022-08-07 18:32 UTC, mattip commented
Thanks @ZicsX