Correct usage example for np.char.decode docstring  (Issue #22015)
numpy/numpy pull request #22026
Opened 2022-07-22 15:16 UTC by BrentTanKian

2022-07-25 10:07 UTC, mattip reviewed
This looks fine and fixes what looks like a copy-paste error. If you have more energy, the `See Also` link on line 554 is broken. I think it should be 
```
:py:meth:`str.decode`
```

2022-07-25 10:13 UTC, BrentTanKian commented
Hey sure, thanks for the heads up @mattip. I'll take a look and push up the new changes

2022-07-25 13:55 UTC, mattip commented
Nope, the [incantation was wrong](https://app.circleci.com/pipelines/github/numpy/numpy/15223/workflows/20bee806-1166-4df0-9545-774cb70b50ca/jobs/27332?invite=true#step-108-233). I misled you, the method is `bytes.decode` (there is no `str.decode`).

It seems you also picked up a stray change in a different file, you might need to rebase and force-push or merge main back into the branch

2022-07-25 14:37 UTC, BrentTanKian commented
I hope that did the trick. Rebased with the upstream main branch and force pushed, and removed the recent changes

2022-07-25 16:04 UTC, mattip commented
I took the liberty of adding a change of `str.decode` -> `bytes.decode`.

2022-08-11 13:36 UTC, melissawm commented
Hi @BrentTanKian - was this closed by accident? Feel free to reopen if that's the case, and let us know if you need help moving forward. Thanks!

2022-08-11 13:42 UTC, BrentTanKian commented
Hmm I'm not sure. The changes seem to have been finalized and vetted through but they haven't been merged with the master branch yet. Perhaps you could review the changes again, and if it looks good to you, you could merge the changes into master. And I also don't think I have the permissions to reopen the issue

2022-08-18 19:05 UTC, WarrenWeckesser commented
Check out the rendered docstring at [numpy.char.decode](https://output.circle-artifacts.com/output/job/599a9f4b-0f68-4564-b718-ff8327c1261d/artifacts/0/doc/build/html/reference/generated/numpy.char.decode.html#numpy.char.decode).

The code shown in the rendered doc is not valid Python, because `b'ÁÁÁ'` will generate a `SyntaxError`.   Making the entire docstring a raw string by prefixing it with `r`  at https://github.com/numpy/numpy/blob/abbf86b4a2f7692ab74a6c395c4e0a7f953a868d/numpy/core/defchararray.py#L531 should fix that.

2022-08-18 19:07 UTC, WarrenWeckesser requested changes
This needs a few small tweaks, otherwise looks good.

2022-08-18 19:07 UTC, WarrenWeckesser commented on numpy/core/defchararray.py
> +                      b'\x81\x82\xc2\xc1\xc2\x82\x81'])
In an interactive Python shell, when a line is continued, the prompt becomes `... `:
```suggestion
...                   b'\x81\x82\xc2\xc1\xc2\x82\x81'])
```

2022-08-18 19:07 UTC, WarrenWeckesser commented on numpy/core/defchararray.py
> +           b'\x81\x82\xc2\xc1\xc2\x82\x81'], dtype='|S7')
```suggestion
...        b'\x81\x82\xc2\xc1\xc2\x82\x81'], dtype='|S7')
```

2022-08-19 00:37 UTC, BrentTanKian commented
Hey @WarrenWeckesser, I'll take a look and put in these changes some time next week. Will come back to you if I have more questions :)

2022-09-18 15:48 UTC, mattip commented
@BrentTanKian ping

2022-09-18 15:56 UTC, BrentTanKian commented
Hey @mattip, my apologies. Got bogged down by some stuff the last couple of weeks. I'll look to put in the new changes by the end of the week

2022-09-19 06:32 UTC, BrentTanKian commented
Hi @mattip, @WarrenWeckesser, I may have lost the branch/fork that contained all the changes mentioned here, and have created a new pull request (#22309) to factor in all the new code/changes you have mentioned here

2022-09-19 09:00 UTC, seberg commented
Closing, since it is continued in gh-22309.  The push by Matti probably confused you, since you would have had to pull Matti's changes first to continue working on it.

2022-09-19 09:00 UTC, closed without merging