DOC: Add copyto example
numpy/numpy pull request #22292
Opened 2022-09-16 20:14 UTC by dg3192

2022-09-16 20:33 UTC, bsipocz requested changes

2022-09-16 20:33 UTC, bsipocz commented on numpy/core/multiarray.py
> +        A
You need to add the `>>>` to the beginning of each and every command lines, which tells the testing infrastructure which ones are the one to run.
Here and below:
```suggestion
    >>> np.copyto(A, B)
    >>> A
```

2022-09-16 20:33 UTC, bsipocz commented on numpy/core/multiarray.py
> +    >>> B = [1,2,3]
Please follow PEP-8 python formatting, in practice for this pull request means to add a space after each coma.
```suggestion
    >>> B = [1, 2, 3]
```

2022-09-19 08:30 UTC, seberg commented
@dg3192 do you have time to follow up on the comments above?  Applying the changes is good here, but the same changes need to be fixed in a few more places and Brigitta did not mark each one individually.

2022-09-19 18:48 UTC, dg3192 commented
@seberg sure, I updated the example but I am having issues in pushing it back. Could you please help me on how should I do it?  
<img width="429" alt="Screen Shot 2022-09-19 at 11 39 07 AM" src="https://user-images.githubusercontent.com/113710955/191092727-f74b773c-58ad-4fa7-982a-96e17e794e28.png">

2022-09-20 07:55 UTC, seberg commented
@dg3192 since you did a force-push, I assume you figured it out?  There are still a few whitespace issues (e.g. space after comma missing).  Maybe you can try that out?

2022-09-21 21:06 UTC, dg3192 commented
@seberg I saved the changes that you highlighted but somehow I am getting error while pushing the changes. Not sure what should be the next step? Attaching error screenshot for your reference
<img width="617" alt="Screen Shot 2022-09-21 at 2 03 58 PM" src="https://user-images.githubusercontent.com/113710955/191610288-c2723c60-b82f-4fce-9af3-d6c6105dbf79.png">

2022-09-21 21:13 UTC, seberg commented
Maybe you worked on a different computer/setup?  The error says that what is on github appears to be newer than what you have locally.  That can happen when others push, but nobody else seemed to have pushed).

There could be other reasons though.  In any case, if you are sure that what you have locally is correct, simply add a `-f`, `git push -f`.  That is a "forced" push which will throw away any changes on github that are not also on your computer already.

2022-09-21 21:50 UTC, dg3192 commented
Ahh, my laptop got restarted yesterday and I think that's why this issue. I tried forced push as well but this is what I am getting.
<img width="633" alt="Screen Shot 2022-09-21 at 2 49 17 PM" src="https://user-images.githubusercontent.com/113710955/191616854-1aa9731d-a367-47b5-8711-8cf7d7fdd538.png">

2022-09-22 07:34 UTC, seberg commented
Try combining the `--set-upstream` with the `-f` :).

2022-09-22 20:12 UTC, dg3192 commented
@seberg I've forced push the changes. Is there anything else I should do from my end?

2022-09-26 10:49 UTC, seberg commented on numpy/core/multiarray.py
> +       [7, 8, 9]])
```suggestion
           [7, 8, 9]])
```

2022-09-26 11:16 UTC, merged

2022-09-26 18:22 UTC, dg3192 commented
Thank you!

2022-10-06 02:59 UTC, InessaPawson commented
Hi-five on merging your first pull request to NumPy, @dg3192! We hope you stick around! Your choices aren’t limited to programming – you can review pull requests, help us stay on top of new and old  issues, develop educational material, work on our website, add or improve graphic design, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://numpy.org/contribute
Also, consider joining our mailing list. This is a great way to connect with other cool people in our community and be part of important conversations that affect the development of NumPy: https://mail.python.org/mailman/listinfo/numpy-discussion