BUG: Fix boundschecking for logseries
numpy/numpy pull request #22450
Opened 2022-10-18 13:19 UTC by seberg

Logseries previously did not enforce bounds to be strictly exclusive. This leads to incorrect behavior for 0 and 1.  Add a new path to implement the correct bounds-checking.

The NOT_NAN check is removed, since it was never used: The current bounded version always excludes NaNs.

2022-10-18 20:52 UTC, WarrenWeckesser approved these changes
Looks good to me, let's see if @bashtage has any suggestions.

2022-10-18 21:52 UTC, bashtage requested changes
I think the mtrand changes are outside of the allowed scope per NEP19.

2022-10-18 21:53 UTC, bashtage commented
Does the distribution behave sensibly in a neighborhood of 0+?  Or is 0 a special case and other tiny numbers are less reliable?

2022-10-19 06:21 UTC, seberg commented
I have not spelled it out, but the path for 1 hangs, so 1 was never a valid input.  Changing 0 to be excluded would indeed be a change that may be covered by the NEP.
Other tiny numbers work just as well (they always return 1 immediately), I am not sure if there is a loss of precision close to 1, but in that case I still guess this is right and that would be a different enhancement.

2022-10-23 22:40 UTC, charris commented on numpy/random/mtrand.pyx
> +            Shape parameter for the distribution.  Must be in the range [0, 1).
Yes, that seems like a reasonable take.

2022-10-24 07:03 UTC, seberg commented on numpy/random/mtrand.pyx
> +            Shape parameter for the distribution.  Must be in the range [0, 1).
This is only a doc update?  There is no change in behavior.  0 always worked, as pointed out by Warren, 1 never worked it is just explicit now.

2022-10-24 22:04 UTC, merged

2022-10-24 22:05 UTC, charris commented
Thanks Sebastian.