BUG: accept zeros on numpy.random dirichlet function
numpy/numpy pull request #23440
Opened 2023-03-23 20:48 UTC by pcralmeida

Changed `alpha` value error to pass a null value. This way, dirichlet function wont raise a value exception at 0. Also added new `test_dirichlet` function on `numpy.tests.test_matlib.py`.

2023-03-24 05:22 UTC, MatteoRaso commented
Thanks for the PR. Just to let everybody know, this is in reference to #22547.

2023-03-24 05:27 UTC, MatteoRaso commented on numpy/tests/test_matlib.py
> +    dirichlet([5, 9, 0, 8])
```suggestion
def test_dirichlet():
    y = dirichlet([5, 9, 0, 8])
    assert y[2] == 0
```
We don't just want to that the function doesn't throw an error, we also want to show that the function returns the right result when 0 is given as input.

2023-03-24 15:42 UTC, seberg requested changes
Thanks, but all changes here need to be moved around, they should be OK changes, but they are at the wrong spot.

2023-03-25 21:55 UTC, pcralmeida commented on numpy/random/mtrand.pyx
> +            raise ValueError('alpha < 0')
I've added the changes to `generator.pyx` as intended, and also passed the test to the `numpy/random` submodule. However, the test would raise the `alpha = 0` value error from `mtrand.pyx`, so I maintained the changes that were made. The changes now seem OK, but I will wait for your feedback.

2023-03-26 07:49 UTC, seberg commented on numpy/random/mtrand.pyx
> +            raise ValueError('alpha < 0')
The value-error is desired in `mtrand` (strict compatibility).  The tests just need to be different.  We should make sure that generator is tested, not `mtrand` (i.e. not `np.random.diriclet` but `np.random.default_rng().dirichlet`.  Those tests live in a different file.

In a sense, we want to nudge users towards preferring `np.random.default_rng()` anyway, so there is probably not much reason to improve mtrand.

2023-04-06 20:27 UTC, pcralmeida commented on numpy/random/mtrand.pyx
> +            raise ValueError('alpha < 0')
Hey, sorry for the long wait. I've read your comment and I've reverted the changes in `mtrand`. Also fixed the test having `np.random.default_rng()` in account. Hope these changes are good now.

2023-04-09 17:19 UTC, MatteoRaso approved these changes
LGTM.

2023-04-11 07:32 UTC, seberg approved these changes

2023-04-11 07:38 UTC, merged

2023-04-11 07:38 UTC, seberg commented
Thanks for the followup, looks good now.

2023-07-19 03:09 UTC, WarrenWeckesser commented on numpy/random/tests/test_randomstate.py
> +        y = random.default_rng().dirichlet([5, 9, 0, 8])
This is using the result of `default_rng()`, which is a `Generator` instance (not `RandomState`), so this test should not be in this file.  I'll fix this in the pull request I am working on for https://github.com/numpy/numpy/issues/24210.