DOC: Update documentation for user-defined converters in np.genfromtxt
numpy/numpy pull request #23511
Opened 2023-03-31 19:39 UTC by Aryan-Mishra24

Description
This PR updates the documentation for user-defined converters in np.genfromtxt, as requested in issue #23429. The changes include clarifications on the input and output types expected by converters, as well as examples of how to define and use converters in different scenarios.

Changes Made
Added a section on input and output types expected by converters.
Added examples of using converters with different input and output types.
Added a subsection on using converters with structured arrays.
Checklist
 Updated the documentation.
 Added new tests for the updated functionality.
 Passes all existing tests.
 Follows the NumPy code style.
 Updated the release notes, if necessary.
Related Issues
Closes #23429

2023-03-31 19:53 UTC, Aryan-Mishra24 commented
one was meant to be DOC: Update documentation for user-defined converters in np.genfromtxt and the other for copyright-policy-update

2023-04-01 19:26 UTC, MatteoRaso requested changes
Thanks for the PR. A few suggestions to start.

2023-04-01 19:26 UTC, MatteoRaso commented on numpy/lib/_iotools.py
> +
```suggestion
```
No need for this blank line here.

2023-04-01 19:26 UTC, MatteoRaso commented on numpy/lib/_iotools.py
> +    without raising unexpected exceptions.
```suggestion
        Be aware that user-defined converters may receive extraneous inputs
        during the type determination process. In particular, a '1' value will
        be passed to the converter when determining the output dtype. This
        behavior should be considered when writing custom converter functions,
        and users should ensure that their converters can handle such input
        without raising unexpected exceptions.
```
The indentation needs to match the indentation for the rest of the `notes` section.

2023-04-01 19:43 UTC, Aryan-Mishra24 commented
Thanks rookie mistake I know
Noted and won't be repeated

On Sun, 2 Apr, 2023, 12:56 am Matteo Raso, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for the PR. A few suggestions to start.
> ------------------------------
>
> In numpy/lib/_iotools.py
> <https://github.com/numpy/numpy/pull/23511#discussion_r1155158989>:
>
> > @@ -790,8 +790,16 @@ def update(self, func, default=None, testing_value=None,
>          `update` takes the same parameters as the constructor of
>          `StringConverter`, except that `func` does not accept a `dtype`
>          whereas `dtype_or_func` in the constructor does.
> -
> +
>
> ⬇️ Suggested change
>
> -
>
> No need for this blank line here.
> ------------------------------
>
> In numpy/lib/_iotools.py
> <https://github.com/numpy/numpy/pull/23511#discussion_r1155159347>:
>
> > +    Be aware that user-defined converters may receive extraneous inputs
> +    during the type determination process. In particular, a '1' value will
> +    be passed to the converter when determining the output dtype. This
> +    behavior should be considered when writing custom converter functions,
> +    and users should ensure that their converters can handle such input
> +    without raising unexpected exceptions.
>
> ⬇️ Suggested change
>
> -    Be aware that user-defined converters may receive extraneous inputs
> -    during the type determination process. In particular, a '1' value will
> -    be passed to the converter when determining the output dtype. This
> -    behavior should be considered when writing custom converter functions,
> -    and users should ensure that their converters can handle such input
> -    without raising unexpected exceptions.
> +        Be aware that user-defined converters may receive extraneous inputs
> +        during the type determination process. In particular, a '1' value will
> +        be passed to the converter when determining the output dtype. This
> +        behavior should be considered when writing custom converter functions,
> +        and users should ensure that their converters can handle such input
> +        without raising unexpected exceptions.
>
> The indentation needs to match the indentation for the rest of the notes
> section.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/numpy/numpy/pull/23511#pullrequestreview-1367913665>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A62VAIX4WJLCONBAYJVQMJLW7B6OHANCNFSM6AAAAAAWPBWQUQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-20 02:03 UTC, rossbar reviewed
There is still an indentation problem here. Moreover I don't think this is in the right place - `StringConverter` is not intended for direct use in user code.

Since this has been stale for a while, I opened #23787 as a simple alternative.

2023-05-31 09:48 UTC, seberg commented
Superseded by gh-23787 so closing.

2023-05-31 09:48 UTC, closed without merging