DOC: Review and expand docstrings for np.gradient()
numpy/numpy pull request #24509
Opened 2023-08-23 11:49 UTC by rajveer43

Close #17867

2023-08-25 11:17 UTC, rgommers requested changes
Thanks @rajveer43. The test failure on Azure is real, can you please fix the example output @rajveer43?

2023-08-25 11:17 UTC, rgommers commented on numpy/lib/function_base.py
> +    >>> np.gradient(complex_array.real)
No output is shown, so this line isn't useful. Delete it?

2023-08-25 11:17 UTC, rgommers commented on numpy/lib/function_base.py
> +    >>> np.gradient(vector_field_x, x, y)
same, not useful - please delete

2023-09-16 14:07 UTC, rkern commented
I don't see how this relates to #17867. These seem to be random uses of `np.gradient()` without a pedagogical purpose.

2023-09-17 13:52 UTC, rkern commented
Personally? None, to be honest. But the conversation in #17867 brought up these:

> Also some examples for np.gradient in this regard would be very helpful, specifically simple examples like f=x**2, f'x = 2*x, and how to obtain np.gradient to show exactly f'x = 2*x, or f = exp(x), f'x = exp(x).

2023-12-31 08:48 UTC, closed without merging

2023-12-31 08:49 UTC, mdhaber commented
Looks like this is no longer active, and it did not address the issue as recommended, so closing.