BLD: Add flag to f2py to pass arbitrary linker flags.
numpy/numpy pull request #25281
Opened 2023-11-30 15:21 UTC by joshuashaffer

The current way of doing this is by setting the LDFLAGS environment variable. 

The problem with this is that if you build your f2py module as part of a larger build system, a valid LDFLAGS for your Fortran compiler may not be a valid LDFLAGS for your C Compiler and cause, for instance, CMake tests that determine if your compiler produces good executables to fail. Also, CMake doesn't support exporting environment variables, so they must be set by some other means. 

The attached patch adds a flag '-J,' which provides a simple mechanism to resolve this issue. For instance, '-J-static-intel' will invoke the linker with the '-static-intel' flag.

2023-11-30 21:50 UTC, HaoZeke requested changes
Thanks for this @joshuashaffer. Couple of thoughts (without running the PR):
- Currently this adds to the `object_files` section
```python
class MesonTemplate:
    """Template meson build file generation class."""

    def __init__(
        self,
        modulename: str,
        sources: list[Path],
        deps: list[str],
        object_files: list[Path],
        linker_args: list[str],
        c_args: list[str],
        build_type: str,
    ):
        meson_template = MesonTemplate(
            self.modulename,
            self.sources,
            self.dependencies,
            self.extra_objects,
            self.flib_flags,
            self.fc_flags,
            self.build_type,
        )
    builder = build_backend(
        modulename,
        sources,
        extra_objects,
        build_dir,
        include_dirs,
        library_dirs,
        libraries,
        define_macros,
        undef_macros,
        f2py_flags,
        sysinfo_flags,
        fc_flags,
        flib_flags,
        setup_flags,
        remove_build_dir,
        {"dependencies": dependencies},
    )
```

It seems like `flib_flags` would be the natural place for this? Also since the backend is supposed to just call `meson compile -C` without actually using either `extra_objects`.

```python
    def run_meson(self, build_dir: Path):
        setup_command = ["meson", "setup", self.meson_build_dir]
        self._run_subprocess_command(setup_command, build_dir)
        compile_command = ["meson", "compile", "-C", self.meson_build_dir]
        self._run_subprocess_command(compile_command, build_dir)

    def compile(self) -> None:
        self.sources = _prepare_sources(self.modulename, self.sources, self.build_dir)
        self.write_meson_build(self.build_dir)
        self.run_meson(self.build_dir)
        self._move_exec_to_root(self.build_dir)
```

Also, could you add:
- A test in `test_f2py2e.py`
- Some documentation in `f2py/usage.rst`?

2023-12-01 18:50 UTC, joshuashaffer commented
I'm trying to write a test for this, but using '-c' when using the DistUtils backend will cause a warning to be emitted that fails the test. 

https://github.com/numpy/numpy/blob/b4ba8e51cb30eb92edf350371b19490899fdda93/numpy/f2py/_backends/_distutils.py#L15

It seems that just passing it in as part of `flib_flags` instead of `extra_objects` ends up reappending the, now bare, linker options back to the f2py argv.

2023-12-18 06:23 UTC, HaoZeke commented
@joshuashaffer is this necessary after https://github.com/numpy/numpy/pull/25297?

2023-12-24 07:16 UTC, HaoZeke commented
I'm tentatively closing this because #25297 should cover this use case more effectively by adding the options to the `meson.build` instead of just the `f2py` build process.

2023-12-24 07:16 UTC, closed without merging