MAINT: Update environment.yml to match *_requirements.txt
numpy/numpy pull request #25308
Opened 2023-12-04 17:24 UTC by melissawm

No real reason other than I noticed the docs were being built locally on python 3.9 instead of 3.11, which is used in CI. If any of those are incorrect please let me know.

2023-12-04 21:53 UTC, rgommers requested changes
Thanks Melissa. This doesn't look quite right to me. The single `=` is the correct comparison symbol, `==` is not correct. Semantics are not the same compared to PyPI/pip specifiers (e.g., this will install 3.11.0 rather than 3.11.6). The added exact pins are not desired I think.

The only change that seems okay to make here is Python 3.11.x instead of 3.9.x

2023-12-05 13:09 UTC, melissawm commented
Of course you're right, sorry about that !

2023-12-05 20:15 UTC, rgommers commented on environment.yml
> +  - setuptools
We still have some compile tests using `setup.py` (e.g. `_core/tests/test_limited_api.py`), so it makes sense. `setuptools` is installing with `python` by conda anyway, so in practice it doesn't matter much.

2023-12-05 20:17 UTC, rgommers approved these changes
LGTM now, thanks Melissa.

2023-12-05 20:18 UTC, merged