DOC: Add examples to functions in `np.polynomial.hermite`
numpy/numpy pull request #25326
Opened 2023-12-06 15:22 UTC by linus-md

This adds examples for several functions in `np.polynomial.hermite`.

2023-12-11 17:32 UTC, mtsokol requested changes

2023-12-11 18:29 UTC, linus-md commented on vendored-meson/meson
Done

2023-12-12 09:15 UTC, mtsokol approved these changes
LGTM! Please squash the PR into a one commit with `DOC: ...` message.

2023-12-12 13:30 UTC, rgommers approved these changes
Thanks @linus-md, and thanks @mtsokol for reviewing.

2023-12-12 13:30 UTC, merged