DOC: Add more `np.ma` documentation
numpy/numpy pull request #25348
Opened 2023-12-08 18:31 UTC by linus-md

Relates to #21351.

2023-12-13 11:50 UTC, mtsokol requested changes

2023-12-13 11:50 UTC, mtsokol commented on numpy/ma/core.py
> +
remove whitespace

2023-12-13 11:50 UTC, mtsokol commented on numpy/ma/core.py
> +        and will be removed in NumPy 2.0. Please use `round` instead.
I think you wanted to add a deprecation warning to `np.ma.round_` instead of `np.ma.MaskedArray.round`?

2023-12-13 11:50 UTC, mtsokol commented on numpy/ma/extras.py
> +def isin(ar1, ar2, assume_unique=False, invert=False):
Why did you change parameter names? I think `element, test_elements` matches `np.isin`.

2023-12-13 14:37 UTC, mtsokol commented
In the error log there is:
```
ValueError: The section Notes appears twice in  Return a copy of a, rounded to 'decimals' places.
```

There are two `Notes` sections for `_round` right now, but each section should appear only once.

For the deprecation warning that you added it would be better to remove it from Notes section and instead raise an actual warning - please see [`def safe_eval`](https://github.com/numpy/numpy/blob/13766216baf864200202beff4ff1133414f7f97c/numpy/lib/_utils_impl.py#L560) function to add a deprecation:
- Use `.. deprecated:: 2.0` in the docstring
- Add `warnings.warn(...)` at the beginning of the function.

Let me know

2023-12-13 14:51 UTC, linus-md commented
So there is already this warning ``<stdin>:1: DeprecationWarning: `round_` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `round` instead.``and I thought it would be useful to add a note.

But where does this happen?

2023-12-13 14:56 UTC, mtsokol commented
Hm, could you paste in a comment a code snippet that displays this warning?

2023-12-13 15:08 UTC, linus-md commented
```
>>> import numpy.ma as ma
>>> mask = [0, 0, 0, 1]
>>> x = [11.2, -3.973, 0.801, -1.41]
>>> masked_x = ma.masked_array(x, mask)
>>> ma.round_(masked_x, decimals=2)
<stdin>:1: DeprecationWarning: `round_` is deprecated as of NumPy 1.25.0, and will be removed in NumPy 2.0. Please use `round` instead.
masked_array(data=[11.2, -3.97, 0.8, --],
             mask=[False, False, False,  True],
       fill_value=1e+20)
>>> 
```

2023-12-13 15:25 UTC, mtsokol commented
I think you're using here some old NumPy version instead of your local instance (this warning was removed some time ago). You can follow [local setup](https://numpy.org/doc/stable/dev/index.html#contributing-to-numpy) instructions, and run IPython interpreter with `spin ipython`.

2023-12-13 15:29 UTC, linus-md commented
Found it: https://github.com/numpy/numpy/pull/23302/files it is in ``fromnumeric.py``in line 3816 and following.

2023-12-13 15:57 UTC, linus-md commented
Ok. Is there anything left to do then or is everything ok?

2023-12-13 16:01 UTC, mtsokol commented
Just last thing: please rebase to examples executing correctly and it's good to go!

2023-12-13 20:04 UTC, linus-md commented
Some git things are really going wrong here. @mtsokol can this be salvaged? Somehow the changes from ``laguerre.py`` ended up here during rebasing.

2023-12-17 19:32 UTC, ngoldbaum commented
@linus-md I'd encourage you to run through some git tutorials on your own to work out how to fix this. If you want to have this many PRs open simultaneously you're going to need to learn how to do it without getting confused - both for your and your reviewers' sake...

If you feel like the history of a pull request is getting messed up, it's OK to just start over from scratch. That's often the easiest way to fix things.

I've also often found ohshitgit.com to be helpful for figuring out how to fix something I've broken in a git repo.

I'd also encourage you to learn how to edit history so your PRs don't mostly end up as fixup commits.

Finally, please pay attention to the commit message formatting guidelines: https://numpy.org/doc/stable/dev/development_workflow.html#writing-the-commit-message

2023-12-17 19:52 UTC, linus-md commented
@ngoldbaum thank you. I will follow your advice.

2023-12-17 23:34 UTC, linus-md commented
@mtsokol I am sorry for making such a mess. Please see this: #25414.

2023-12-17 23:34 UTC, closed without merging

2023-12-18 09:14 UTC, mtsokol commented
@linus-md no need to sorry! Thanks - I will review the new one!