[MAINT] update all TypedDict imports [skip ci]
numpy/numpy pull request #25352
Opened 2023-12-09 01:59 UTC by rbavery

addresses https://github.com/numpy/numpy/issues/25206 by updating where TypedDict is imported from. This is to address an error pydantic raises when numpy_typing.DTypeLike is used in pydantic v2 BaseModels.

I'm skipping ci since this is my first PR and I'm not sure if I should skip some of the CI described here given that the change is minimal: https://numpy.org/devdocs/dev/development_workflow.html#writing-the-commit-message

2023-12-11 10:20 UTC, rgommers requested changes
Thanks @rbavery. The changes to `.pyi` files look fine to me, but the one to the `_typing/_dtype_like.py` does not. That adds a runtime dependency on `typing_extensions`, which must not be done. `typing_extensions` can only be used at static analysis time. So that import must either be avoided or protected by `if typing.TYPE_CHECKING:`.

2023-12-11 16:22 UTC, BvB93 commented
For the issue in particular the `*.pyi` changes are completely redundant anyway as Pydanticis purely a runtime tool; not a static type checker. The only way to fix this issue would be via the runtime import of `from typing_extensions import TypedDict` (in combination with a try/except block), reintroduction of which I'm admittedly lukewarm about. Especially considering, as was already noted by Ralf, this issue is due to a (overly?) strict typeddict requirement on Pydantics side rather than a numpy bug.

Now, if we're going ahead with the runtime import from typing extensions then we could also really use a reintroduction of this test (xref https://github.com/numpy/numpy/pull/19525) in order to assure we don't accidentally make typing extensions a hard dependency.

2023-12-12 22:35 UTC, rbavery commented
Thanks for the feedback! 

> The only way to fix this issue would be via the runtime import of from typing_extensions import TypedDict (in combination with a try/except block), reintroduction of which I'm admittedly lukewarm about. 

I'll leave it up to the numpy maintainers if this is something that is alright to do. I agree the requirement is overly strict. Unfortunately I don't think pydantic will adjust this behavior since they closed issues related to this pretty emphatically. I don't need to use npt.DtypeLike in pydantic BaseModels but it would be nice if this worked.

https://github.com/pydantic/pydantic/issues/6860#issuecomment-1651005718
https://github.com/pydantic/pydantic/issues/6645#issuecomment-1634282750

2025-04-04 15:51 UTC, jorenham reviewed
But with this change an `ImportError` will be raised if you `import numpy.typing as npt` and don't have `typing_extensions` installed. So this would require adding `typing_extensions` as (the only) runtime dependency: A big change in NumPy for a small problem in Pydantic.

I explained in https://github.com/numpy/numpy/issues/25206#issuecomment-2779006764, that it's pretty easy to define your own flavor of `DTypeLike` that is supported by Pydantic. To me that seems like a pretty reasonable solution for this problem.

The changes in the `*.pyi` are technically possible, but serve no purpose &mdash; it has no effect on the behaviour of static type-checkers. 

So I propose that we close this PR and linked issue. If anyone objects or if I missed something, we can re-open this.

2025-04-04 15:52 UTC, closed without merging