DOC: Add missing examples to ``np.ma``
numpy/numpy pull request #25414
Opened 2023-12-17 23:33 UTC by linus-md

Relates to #21351. See also: #25348.

2023-12-18 09:42 UTC, mtsokol requested changes
Just a couple of nitpicks and it's ready to go!

2023-12-18 09:42 UTC, mtsokol commented on numpy/ma/core.py
> +        >>> x = np.ma.array([1.35, 2.5, 1.5, 1.75, 2.25, 2.75],
You imported `ma` so you can do `x = ma.array(....` for consistency with existing examples in `ma/core.py`.

2023-12-18 09:42 UTC, mtsokol commented on numpy/ma/extras.py
> +    >>> x = np.ma.array(np.arange(9).reshape(3, 3), mask=[[1, 0, 0],
Same as above.

2023-12-18 09:42 UTC, mtsokol commented on numpy/ma/extras.py
> +    >>> np.ma.setxor1d(ar1, ar2)
Same here, no need for `np.`.

2023-12-18 09:42 UTC, mtsokol commented on numpy/ma/extras.py
> +    >>> ar1 = np.ma.array([0, 1, 2, 5, 0])
Same here.

2023-12-18 09:42 UTC, mtsokol commented on numpy/ma/extras.py
> +    >>> np.in1d(ar1, ar2)
I think you should use `ma.in1d`. This example doesn't use `in1d` from the `ma` module.

2023-12-18 09:42 UTC, mtsokol commented on numpy/ma/extras.py
> +    >>> np.ma.isin(element, test_elements)
Same here, no need for `np.`.

2023-12-18 09:42 UTC, mtsokol commented on numpy/ma/extras.py
> +    >>> np.ma.union1d(ar1, ar2)
Same here.

2023-12-18 10:24 UTC, linus-md commented on numpy/ma/extras.py
> +    >>> np.ma.union1d(ar1, ar2)
All done @mtsokol!

2023-12-21 09:57 UTC, mtsokol approved these changes

2023-12-23 19:41 UTC, merged

2023-12-23 19:41 UTC, mattip commented
Thanks @linus-md