BUG: don't fail hard when parsing version in GnuFCompiler
numpy/numpy pull request #26502
Opened 2024-05-22 14:36 UTC by Flamefire

When the version could not be determined `None` is supposed to be returned.

However `gnu_version_match` raises an error which leads to hard failures when a "wrong" Fortran compiler is found/used instead of gracefully disabling it which would be completely fine when a Fortran compiler is never used/required.

It is even expected to return `None` as indicated by checks like: https://github.com/numpy/numpy/blob/aad6c9cd1958309110f9892d10b28b1beea9c670/numpy/distutils/fcompiler/gnu.py#L77-L78

2024-05-22 14:57 UTC, rgommers requested changes
I'm afraid we're not going to change this anymore (this code is deprecated and will disappear at some point). If a Fortran compiler is needed, it should be found - the error is on purpose. And the only place it's still used _by default_ is in `numpy.f2py`, for which a Fortran compiler is mandatory.

You also picked up a git submodule change here.

2024-05-22 15:23 UTC, Flamefire commented
> You also picked up a git submodule change here.

Fixed.

> I'm afraid we're not going to change this anymore (this code is deprecated and will disappear at some point). If a Fortran compiler is needed, it should be found - the error is on purpose.

Then it is very strange that the error is only in the Gnu compiler. Every other compiler uses a matcher which returns `None` or provides a `version_pattern` which also results in `None` on a non-match. See the using code at https://github.com/numpy/numpy/blob/aad6c9cd1958309110f9892d10b28b1beea9c670/numpy/distutils/ccompiler.py#L609

So isn't that surprising / inconsistent? Especially as e.g. `fcompiler.get_default_fcompiler` is made to return `None` when a compiler can't be found: https://github.com/numpy/numpy/blob/aad6c9cd1958309110f9892d10b28b1beea9c670/numpy/distutils/fcompiler/__init__.py#L834-L838

> And the only place it's still used _by default_ is in `numpy.f2py`, for which a Fortran compiler is mandatory.

Ok not sure if there are any other paths  which might lead to this, especially as there is the `requiref90` parameter to `get_default_fcompiler`

2024-05-22 15:57 UTC, ngoldbaum commented
The distutils code is quite dusty and full of issues like this, which is the main reason why it's deprecated and scheduled to be removed completely once Python 3.11 falls out of our support window.

2024-05-23 07:57 UTC, rgommers commented
@Flamefire we won't merge this without a very compelling reason. It's not even clear to me that you are using the code you are changing here, because your original issue was about `pip install` and `python setup.py install`, both of which don't use this code. Please do explain if this change is actually a hard necessity for you for some reason.

2024-05-23 10:06 UTC, Flamefire commented
`python setup.py install` does use this code and that is what we are using and what is blocking us from using non-GCC compilers unless we pass the right `--fcompiler` option which seems not necessary given that Fortran isn't used to build numpy.

Traceback:
```
 [...]
  File "/software/Python/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/build/numpy/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/build/numpy/numpy/distutils/command/build_src.py", line 155, in build_sources
    self.build_library_sources(*libname_info)
  File "/build/numpy/numpy/distutils/command/build_src.py", line 288, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/command/build_src.py", line 378, in generate_sources
    source = func(extension, build_dir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/core/setup.py", line 671, in get_mathlib_info
    mlibs = check_mathlib(config_cmd)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/core/setup.py", line 389, in check_mathlib
    if config_cmd.check_func(
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/command/config.py", line 321, in check_func
    self._check_compiler()
  File "/build/numpy/numpy/distutils/command/config.py", line 79, in _check_compiler
    self.fcompiler = new_fcompiler(compiler=self.fcompiler,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/__init__.py", line 892, in new_fcompiler
    compiler = get_default_fcompiler(plat, requiref90=requiref90,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/__init__.py", line 863, in get_default_fcompiler
    compiler_type =  _find_existing_fcompiler(matching_compiler_types,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/__init__.py", line 814, in _find_existing_fcompiler
    c.customize(dist)
  File "/build/numpy/numpy/distutils/fcompiler/__init__.py", line 510, in customize
    get_flags('opt', oflags)
  File "/build/numpy/numpy/distutils/fcompiler/__init__.py", line 501, in get_flags
    flags.extend(getattr(self.flag_vars, tag))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/environment.py", line 40, in __getattr__
    return self._get_var(name, conf_desc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/environment.py", line 56, in _get_var
    var = self._hook_handler(name, hook)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/__init__.py", line 715, in _environment_hook
    return hook()
           ^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/gnu.py", line 225, in get_flags_opt
    v = self.get_version()
        ^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/__init__.py", line 429, in get_version
    version = CCompiler.get_version(self, force=force, ok_status=ok_status)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/ccompiler.py", line 91, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/ccompiler.py", line 670, in CCompiler_get_version
    version = matcher(output)
              ^^^^^^^^^^^^^^^
  File "/build/numpy/numpy/distutils/fcompiler/gnu.py", line 274, in version_match
    v = self.gnu_version_match(version_string)
```

2024-05-23 10:16 UTC, closed without merging

2024-05-23 10:17 UTC, rgommers commented
> `python setup.py install` does use this code

As I said, `setup.py` is gone. To pick an example from your traceback:
```
File "/build/numpy/numpy/core/setup.py", line 671, in get_mathlib_info
```
that file no longer exists.

Maybe you are trying to build some old version of numpy. If so, please apply the patch you need locally.