Adding P.coeffs property
numpy/numpy pull request #27232
Opened 2024-08-17 00:17 UTC by olcc

Hello,
This is an enhancement adding a `coeffs` property to polynomials, as discussed in https://github.com/numpy/numpy/issues/26401.
The reason is that a lot of people get confused by `P.coef`, because this is not the coefficients they are looking for. This new property will offer them an easy access to `P.convert().coef`, i.e. what they are actually looking for, and explain the difference with `P.coef`.
Best regards,
Olivier

2024-08-17 15:52 UTC, mhvk requested changes
I was not part of the discussion in #26401, but I think adding a new property with a very similar name is a bad idea. I think more generally that better documentation is the answer, but that discussion is probably better had in #26401, so I'll comment there.

Note that generally one should write to the mailing list for API changes; given the disagreement about whether this is worthwhile in #26401, this is probably a change that should get that wider exposure.

p.s.  I put "request changes" just for the name.

2024-08-17 16:04 UTC, rkern commented
Yeah, the mailing list is probably the right forum to hash this out. It's good to have a PR open with the current proposal to make things concrete, though, so no worries about the order of operations here.

FWIW, I agree that the `coeffs/coef` pairing is not ideal. One of the more descriptive variants like `natural_coef` would be my vote for the bikeshed color when the mailing list thread arises.

2024-08-17 18:56 UTC, jorenham requested changes
Don't forget to also update the [typing stubs](https://github.com/numpy/numpy/blob/main/numpy/polynomial/_polybase.pyi)

2024-08-18 16:15 UTC, olcc commented
> One of the more descriptive variants like `natural_coef`

I proposed `coeffs` because it is the name used in Sympy for that purpose (return the coefficients for the natural variable).

If this name is not appreciated, I would propose `coef_natural` (which I prefer to `natural_coef` for auto-completion practicality).

2024-09-24 11:50 UTC, jorenham reviewed
the typing stubs look fine

2024-10-10 19:51 UTC, olcc commented
Hello,
I exposed the question on the mailing list. No clear answer came from it. There are still two possibilities:
(A) Create a new property: add a `P.coef_natural` property, with a suitable documentation ; maybe also add a `P.coef_internal` property. There would be no change to the existing code (only addition of properties). 
(B) Change `P.coef` attribute into a property, with a suitable documentation. Hide `P.coef` attribute into `P._coef` (change existing code). Do not create more properties (unlike A). This does not change the API.

So, what do we do? I feel that people prefer (B) because they are wary of any API change. However the current Pull Request implements (A).

2024-10-10 21:06 UTC, mhvk commented
As per the discussion in #26401 and on the mailing list, I'm still :-1: on adding a direct way to access the "natural" coefficients. They are computationally suspect and *not* natural for many of the polynomial classes. I strongly feel we should go route (b), or hiding `coefs` behind a property so that it can be properly documented.

2024-10-10 21:40 UTC, olcc commented
OK for option (B). 
How do I do ? I create another PR and you close this one?

2024-10-10 23:26 UTC, mhvk commented
> OK for option (B). How do I do ? I create another PR and you close this one?

Yes, I think a separate PR is cleaner. Thanks for your patience with this!

2024-10-10 23:26 UTC, closed without merging