MAINT: Start applying ruff/Pyflakes rules (F)
numpy/numpy pull request #27309
Opened 2024-08-29 11:59 UTC by DimitriPapadopoulos

In preparation for https://github.com/numpy/numpy/issues/24994.

The purpose of this PR is to show the kind of changes involved by `F` rules, which ruff enables by default. The idea is not necessarily to apply these rules, but to support a discussion whether it is worth applying these rules or rather disabling them , if pycodestyle was replaced by ruff.

2025-04-18 14:17 UTC, DimitriPapadopoulos commented on numpy/_core/tests/_natype.py
> +        exponent = 31 if is_32bit else 61  # FIXME  # noqa: F821
What the heck is `is_32bit`? I cannot find it anywhere in Numpy or Python.

2025-04-18 14:17 UTC, DimitriPapadopoulos commented on numpy/_core/tests/_natype.py
> +        elif util.is_array(other):  # FIXME  # noqa: F821
I cannot find `util` or `is_array` anywhere. Where do these come from?

2025-04-18 14:17 UTC, DimitriPapadopoulos commented on numpy/_core/tests/_natype.py
> +        result = maybe_dispatch_ufunc_to_dunder_op(  # noqa: F821
I cannot find where `maybe_dispatch_ufunc_to_dunder_op` is supposed to be defined.

2025-04-18 14:17 UTC, DimitriPapadopoulos commented on numpy/_core/tests/test_overrides.py
> -
Exact duplicate of the above function.

2025-04-18 14:17 UTC, DimitriPapadopoulos commented on numpy/_core/tests/test_ufunc.py
> +    def test_signature_dtype_instances_allowed_2(self, get_kwarg):
The preceding test function had the same name. Can you help find a better name?

2025-04-18 19:53 UTC, DimitriPapadopoulos commented on numpy/_core/tests/test_ufunc.py
> +    def test_signature_dtype_instances_allowed_2(self, get_kwarg):
It turns out the previous test function is obsolete — enabling it results in errors. Will only keep the second one.

2025-04-19 19:53 UTC, jorenham requested changes
I noticed that there are a lot of `F401` ([unused-import](https://docs.astral.sh/ruff/rules/unused-import/#unused-import-f401)) ignores. Maybe we should just disable it structurally, e.g. for all `__init__.py` in the `lint.extend-per-file-ignores`?

2025-04-19 19:53 UTC, jorenham commented on benchmarks/benchmarks/bench_array_coercion.py
> -        np.asarray(array_like, dtype=self.int64)
`order="F"` has an impact on performance, so it should probably stay

2025-04-19 19:53 UTC, jorenham commented on numpy/_core/_add_newdocs.py
> +from numpy._core.overrides import get_array_function_like_doc  # noqa: F401
it might be an implicit re-export, but you'd have to code-search it to be sure

2025-04-19 19:53 UTC, jorenham commented on numpy/_core/arrayprint.py
> +from .numerictypes import (int_, float64, complex128, flexible)
```suggestion
from .numerictypes import int_, float64, complex128, flexible
```

2025-04-19 19:53 UTC, jorenham commented on numpy/_core/multiarray.py
> +    _get_madvise_hugepage, _set_madvise_hugepage,  # noqa: F401
since it would require 10 or so `# noqa` after a `ruff format`, it should probably be a global `# ruff: noqa`

2025-04-19 19:53 UTC, jorenham commented on numpy/_core/tests/test_ufunc.py
> -
the test below with the same name looks different to me

2025-04-19 19:53 UTC, jorenham commented on numpy/core/__init__.py
> +# ruff: noqa: F822
which of the exports are undefined?

2025-04-19 19:53 UTC, jorenham commented on numpy/lib/array_utils.py
> +# flake8: noqa: F401
not `ruff`?

2025-04-19 19:53 UTC, jorenham commented on numpy/lib/user_array.py
> +# flake8: noqa: F401
```suggestion
# ruff: noqa: F401
```

2025-04-19 19:53 UTC, jorenham commented on numpy/ma/core.py
> -from numpy import array as narray, expand_dims, iinfo, finfo
this looks like something that could break some downstream code

2025-04-19 19:53 UTC, jorenham commented on numpy/ma/extras.py
> +    nomask, sort, zeros, getdata, dot
this feels a bit risky to me, given that we're in a public module

2025-04-19 19:53 UTC, jorenham commented on ruff.toml
> +"__init__.py" = ["F401"]
usually you inline `# ruff: noqa` this one, so why the exception?

2025-04-19 19:53 UTC, jorenham commented on ruff.toml
> +    "F405",  # may be undefined, or defined from star imports
In my experience these errors usually occur in `__init__.py` files. Perhaps it could be moved to the `per-file-ignores`?

2025-04-19 19:53 UTC, jorenham commented on ruff.toml
> +    "F821",  # Undefined name
Checking for undefined names seems pretty useful to me; why did you disable it?

2025-04-19 19:53 UTC, jorenham commented on ruff.toml
Some of the current comments are difficult to understand if you don't know what the codes are for. So especially for those, it could be helpful to include the human-readable ruff error-code names as comments. Personally I always do this in all of my own projects (too many), and I found it to be quite helpful. See e.g. https://github.com/numpy/numtype/blob/main/src/numpy-stubs/.ruff.toml

2025-04-19 20:00 UTC, jorenham commented
In [numtype](https://github.com/numpy/numtype/tree/main) I've been using nested (hierarchical) `.ruff.toml` quite a bit. It avoids the main ruff config from becoming too monolithic when there are many per-file-ignores. For example in the `src/numpy-stubs/@test` dir I places a `.ruff.toml` with the contents

```pyi
extend = "../../../pyproject.toml"
line-length = 88

[lint]
extend-ignore = [
    "D",       # pydocstyle
    "ERA",     # eradicate
    "S",       # flake8-bandit
    "T",       # flake8-print
    "PLR2004", # pylint: magic-value-comparisons
]
```

Perhaps something like that could also help for numpy?

2025-04-21 08:48 UTC, DimitriPapadopoulos commented on ruff.toml
> +    "F821",  # Undefined name
It's temporary. Too many changes, and many of them break CI. I'd rather apply them in a dedicated PR. Meanwhile, I'll add a `TODO`.

2025-04-21 08:52 UTC, DimitriPapadopoulos commented on ruff.toml
> +"__init__.py" = ["F401"]
I don't know. Ignoring F401 in `__init__.py` files is pretty common, so I added this upfront. The rest is the result of gradually changing "too many" lines with `noqa:` into a single `ruff: noqa:`. I agree I should be consistent. Which style do you prefer? In the file itself or `pyproject.toml`?

2025-04-21 08:53 UTC, DimitriPapadopoulos commented on numpy/lib/array_utils.py
> +# flake8: noqa: F401
Both work, but of course I need to change to `ruff` for consistency.

2025-04-21 08:53 UTC, DimitriPapadopoulos commented on numpy/_core/multiarray.py
> +    _get_madvise_hugepage, _set_madvise_hugepage,  # noqa: F401
Yes, i'll fix that.

2025-04-21 08:55 UTC, DimitriPapadopoulos commented on benchmarks/benchmarks/bench_array_coercion.py
> -        np.asarray(array_like, dtype=self.int64)
Then I'll add the suffix _order_F to the test name.

2025-04-21 09:13 UTC, DimitriPapadopoulos commented on numpy/_core/_add_newdocs.py
> +from numpy._core.overrides import get_array_function_like_doc  # noqa: F401
It is re-exported by `_core`:
https://github.com/numpy/numpy/blob/851ba152cbda769ca672e242d7ac65af18242f52/numpy/_core/__init__.py#L94-L97

On the other hand The function is not being used directly:
```console
$ grep -R get_array_function_like_doc
numpy/_core/function_base.py:            doc = overrides.get_array_function_like_doc(new, doc)
numpy/_core/overrides.py:def get_array_function_like_doc(public_api, docstring_template=""):
numpy/_core/overrides.py:    public_api.__doc__ = get_array_function_like_doc(public_api)
numpy/_core/overrides.pyi:def get_array_function_like_doc(public_api: Callable[..., Any], docstring_template: str = "") -> str: ...
numpy/_core/_add_newdocs.pyi:from .overrides import get_array_function_like_doc as get_array_function_like_doc
numpy/_core/_add_newdocs.py:from numpy._core.overrides import get_array_function_like_doc  # noqa: F401
```

2025-04-21 09:27 UTC, DimitriPapadopoulos commented on numpy/_core/_add_newdocs.py
> +from numpy._core.overrides import get_array_function_like_doc  # noqa: F401
This import was added by https://github.com/numpy/numpy/pull/16935 / 4cd6e4b336fbc68d88c0e9bc45a435ce7b721f1f.
```
DOC: Add set_array_function_like_doc function
```
It's still unclear why the re-export would be needed.

2025-04-21 09:39 UTC, DimitriPapadopoulos commented on numpy/_core/tests/test_ufunc.py
> -
Yes, it **is** different. Could they be merged? I'm not familiar with adding ids with `param(...., id="...")`.

2025-04-21 09:46 UTC, DimitriPapadopoulos commented on numpy/core/__init__.py
> +# ruff: noqa: F822
All of `__all__`, which is not surprising:
https://github.com/numpy/numpy/blob/851ba152cbda769ca672e242d7ac65af18242f52/numpy/core/__init__.py#L22

<details>
<summary>ruff check error F822</summary>

```console
$ ruff check
numpy/core/__init__.py:24:12: F822 Undefined name `arrayprint` in `__all__`
   |
22 | # force lazy-loading of submodules to ensure a warning is printed
23 |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
   |            ^^^^^^^^^^^^ F822
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
   |

numpy/core/__init__.py:24:26: F822 Undefined name `defchararray` in `__all__`
   |
22 | # force lazy-loading of submodules to ensure a warning is printed
23 |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
   |                          ^^^^^^^^^^^^^^ F822
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
   |

numpy/core/__init__.py:24:42: F822 Undefined name `_dtype_ctypes` in `__all__`
   |
22 | # force lazy-loading of submodules to ensure a warning is printed
23 |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
   |                                          ^^^^^^^^^^^^^^^ F822
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
   |

numpy/core/__init__.py:24:59: F822 Undefined name `_dtype` in `__all__`
   |
22 | # force lazy-loading of submodules to ensure a warning is printed
23 |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
   |                                                           ^^^^^^^^ F822
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
   |

numpy/core/__init__.py:25:12: F822 Undefined name `einsumfunc` in `__all__`
   |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
   |            ^^^^^^^^^^^^ F822
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |

numpy/core/__init__.py:25:26: F822 Undefined name `fromnumeric` in `__all__`
   |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
   |                          ^^^^^^^^^^^^^ F822
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |

numpy/core/__init__.py:25:41: F822 Undefined name `function_base` in `__all__`
   |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
   |                                         ^^^^^^^^^^^^^^^ F822
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |

numpy/core/__init__.py:25:58: F822 Undefined name `getlimits` in `__all__`
   |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
   |                                                          ^^^^^^^^^^^ F822
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |

numpy/core/__init__.py:26:12: F822 Undefined name `_internal` in `__all__`
   |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
   |            ^^^^^^^^^^^ F822
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |

numpy/core/__init__.py:26:25: F822 Undefined name `multiarray` in `__all__`
   |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
   |                         ^^^^^^^^^^^^ F822
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |

numpy/core/__init__.py:26:39: F822 Undefined name `_multiarray_umath` in `__all__`
   |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
   |                                       ^^^^^^^^^^^^^^^^^^^ F822
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |

numpy/core/__init__.py:26:60: F822 Undefined name `numeric` in `__all__`
   |
24 | __all__ = ["arrayprint", "defchararray", "_dtype_ctypes", "_dtype",
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
   |                                                            ^^^^^^^^^ F822
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |

numpy/core/__init__.py:27:12: F822 Undefined name `numerictypes` in `__all__`
   |
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |            ^^^^^^^^^^^^^^ F822
28 |
29 | def __getattr__(attr_name):
   |

numpy/core/__init__.py:27:28: F822 Undefined name `overrides` in `__all__`
   |
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |                            ^^^^^^^^^^^ F822
28 |
29 | def __getattr__(attr_name):
   |

numpy/core/__init__.py:27:41: F822 Undefined name `records` in `__all__`
   |
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |                                         ^^^^^^^^^ F822
28 |
29 | def __getattr__(attr_name):
   |

numpy/core/__init__.py:27:52: F822 Undefined name `shape_base` in `__all__`
   |
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |                                                    ^^^^^^^^^^^^ F822
28 |
29 | def __getattr__(attr_name):
   |

numpy/core/__init__.py:27:66: F822 Undefined name `umath` in `__all__`
   |
25 |            "einsumfunc", "fromnumeric", "function_base", "getlimits",
26 |            "_internal", "multiarray", "_multiarray_umath", "numeric",
27 |            "numerictypes", "overrides", "records", "shape_base", "umath"]
   |                                                                  ^^^^^^^ F822
28 |
29 | def __getattr__(attr_name):
   |

Found 17 errors.
$ 
```
</details>

2025-04-21 09:51 UTC, DimitriPapadopoulos commented on numpy/ma/core.py
> -from numpy import array as narray, expand_dims, iinfo, finfo
Indeed, it's part of the public API, whether it's a good idea or not. Fixing it.

2025-04-21 09:52 UTC, DimitriPapadopoulos commented on numpy/ma/extras.py
> +    nomask, sort, zeros, getdata, dot
Same. Fixing it.

2025-04-21 09:54 UTC, DimitriPapadopoulos commented on ruff.toml
Yes, I have already started fixing that in `ruff.toml`.

2025-04-21 09:56 UTC, DimitriPapadopoulos commented on ruff.toml
> +    "F405",  # may be undefined, or defined from star imports
Let me give it a try.

2025-04-21 10:01 UTC, DimitriPapadopoulos commented on ruff.toml
> +    "F405",  # may be undefined, or defined from star imports
I'm still getting 487 errors instead of 562, only 75 of them originate in `__init__.py` files. However, they occur in only 8 files, for which I can easily add per-file excludes:
```
numpy/_core/defchararray.py
numpy/_core/multiarray.py
numpy/_core/numeric.py
numpy/_core/umath.py
numpy/f2py/capi_maps.py
numpy/f2py/crackfortran.py
numpy/f2py/f90mod_rules.py
numpy/matlib.py
```

2025-04-21 10:45 UTC, DimitriPapadopoulos commented
I'm not sure how to use [mypy_primer](https://github.com/hauntsaninja/mypy_primer), there weren't too many typing-related changes here. I have rebased just in case.

2025-04-21 11:08 UTC, DimitriPapadopoulos commented on numpy/_core/tests/test_ufunc.py
> -
Actually, see my previous comment https://github.com/numpy/numpy/pull/27309#discussion_r2051055976.

That test function had clearly **not** been executed for quite a long time — if ever. Enabling it by changing its name results in such errors:
```
  E       AttributeError: module 'numpy' has no attribute 'timedelta'. Did you mean: 'timedelta64'?
```

2025-04-21 13:39 UTC, jorenham commented
> Diff from [mypy_primer](https://github.com/hauntsaninja/mypy_primer?rgh-link-date=2025-04-21T11%3A21%3A54Z), showing the effect of this PR on type check results on a corpus of open source code:
> 
> ```diff
> vision (https://github.com/pytorch/vision)
> - torchvision/utils.py:271: error: Unused "type: ignore" comment  [unused-ignore]
> ```

🤷🏻

2025-04-21 13:49 UTC, jorenham commented on numpy/_core/_add_newdocs.py
> +from numpy._core.overrides import get_array_function_like_doc  # noqa: F401
If removing this is a problem, then it would show up if you diff the built docs. I don't know much about the docs myself though.

2025-04-30 22:30 UTC, DimitriPapadopoulos commented
Rebased to fix conflicts.

2025-04-30 23:57 UTC, jorenham approved these changes

2025-05-01 17:27 UTC, jorenham commented
needs another rebase

2025-05-01 18:53 UTC, DimitriPapadopoulos commented
Rebased to fix conflicts.

2025-05-11 11:20 UTC, DimitriPapadopoulos commented
Rebased.

2025-05-12 17:00 UTC, jorenham commented
> Rebased.

it needs another, I'm afraid

2025-05-12 17:00 UTC, jorenham approved these changes

2025-05-12 19:05 UTC, DimitriPapadopoulos commented
Rebased.

2025-05-12 20:13 UTC, merged

2025-05-12 20:14 UTC, jorenham commented
Thanks Dimitri