ENH: Improve performance of np.count_nonzero for float arrays
numpy/numpy pull request #27523
Opened 2024-10-07 11:48 UTC by eendebakpt

Improve performance of `np.count_nonzero` for float arays. The PR is similar to https://github.com/numpy/numpy/pull/18183, but uses a simple loop instead of SIMD instructions.

* The template in `arraytypes.c.src` has more types than is strictly required (the integers have their own fast path), these can be removed if needed.

Quick benchmark:
```
import sys
import timeit
import numpy as np

b = np.arange(10_000).astype(bool)
x = b.astype(int)
f = b.astype(np.float64)
f32 = b.astype(np.float32)
n=10

for A in [b, x, f, f32]:
    t = timeit.timeit('np.count_nonzero(A)', globals=globals(), number=n)
    print(f'{A.dtype}: {1e6*t/n:.1f} [us]')
```
Main:
```
bool: 1.5 [us]
int64: 5.1 [us]
float64: 24.8 [us]
float32: 28.0 [us]
``` 
PR
``` 
bool: 1.5 [us]
int64: 5.1 [us]
float64: 7.8 [us]
float32: 7.7 [us]
```

2024-10-08 18:21 UTC, charris commented
close/reopen for testing.

2025-02-10 09:14 UTC, eendebakpt commented
@tylerjereddy Would you me able to review this PR?

2025-02-11 01:10 UTC, tylerjereddy reviewed
Could you add `asv` benchmarks to guard the performance improvement? When I run `asv continuous -e -b "time_count_nonzero.*" main count_nonzero_float` locally, I don't see any sign of improvements, probably because I don't see any benchmark parametrization over float types, so maybe we could include them.

The floating code path might be less common than the integer code paths since checking if a float is *exactly* zero may be a bit more annoying? I suppose that might be a point of potential resistance from the other core devs? Though the shims seem fairly small-ish.

2025-02-11 01:10 UTC, tylerjereddy commented on numpy/_core/src/multiarray/arraytypes.c.src
> +         * #dtype = npy_bool, npy_byte, npy_byte, npy_uint16, npy_int16, npy_uint32, npy_int32, npy_uint64, npy_int64, npy_float, npy_double#
I think you can purge this line since there is no substitution target for `dtype` in the repeated block? At least when I do that locally a clean build from source still passes the full suite.

2025-02-11 10:18 UTC, seberg requested changes
Changes look good to me, thanks.

Please add a test for byte swapped floats (or point to one if it is fine).  The code doesn't look like it deals with that correctly (it is completely fine to just take the slow path for all byte-swapped dtypes, although it is OK for integers of course).

2025-02-11 10:18 UTC, seberg commented on numpy/_core/src/multiarray/item_selection.c
> +                return dispatched_nonzero_count;
```suggestion
            if (dispatched_nonzero_count >= 0) {
                return dispatched_nonzero_count;
            }
```

2025-02-11 10:18 UTC, seberg commented on numpy/_core/src/multiarray/arraytypes.c.src
> +}
I suppose the only reason for putting it here is that the other file isn't `c.src` (or `.cpp` for that matter).

(OK with me)

2025-02-11 10:18 UTC, seberg commented on numpy/_core/src/multiarray/arraytypes.c.src
> +npy_intp
```suggestion
NPY_NO_EXPORT npy_intp
```
not sure we fixed that... Once that happens we should just remove this throughout (rather than stop adding it), IMO.

2025-02-11 11:10 UTC, seberg commented
I forgot to point out that the important thing about byte swapping is a byte-swapped `-0.0` not a `0`, since it actually _is_ all zero.

2025-02-21 08:20 UTC, seberg commented on numpy/_core/src/multiarray/item_selection.c
> +            if (PyArray_ISNOTSWAPPED(self)) {
Just realized (for reasons): Basically every time you check something like this you also need to check whether the array is aligned.  The above code does that, as you can see.

(Please also check in the other PR.  One way to test in CI could be to use a `"?d"` structured dtype, another to just `view` with a byte shift.  The structured dtype just doesn't check if there is a contiguous only special loop.)

2025-02-23 20:36 UTC, eendebakpt commented on numpy/_core/src/multiarray/item_selection.c
> +            if (PyArray_ISNOTSWAPPED(self)) {
Do you mean we should replace `PyArray_ISNOTSWAPPED(self)` with `PyArray_ISALIGNED(self) && PyArray_ISNOTSWAPPED(self)`? What would be the reason for this check?

2025-02-24 11:39 UTC, seberg commented on numpy/_core/src/multiarray/item_selection.c
> +            if (PyArray_ISNOTSWAPPED(self)) {
Dereferencing an unaligned pointer like `*(float64 *)ptr` will just kill with a SIGBUS or something on come hardware (it may be slow on others).
It isn't a problem on typical hardware...

Dunno, I think some snaitizer (UBSAN?) would find it, otherwise the typical thing is that debian opens an issue eventually because there is a SIGBUS on sparc or so.

2025-02-24 11:39 UTC, seberg commented on numpy/_core/tests/test_numeric.py
> +        b = np.zeros(64 + 1).view(np.int8)[1:-(np.intp(0).itemsize - 1)]
`intp` itemsize != float64 itemsize.  Just hardcode the 8/7 bytes, seems easier to read.  Can also create the `int8/uint8` array initially directly.

2025-04-22 08:31 UTC, seberg approved these changes
OK, let's put this in, thanks.  Looks right now, and clean enough.  Thanks for the new tests also, which are important!

I still feel it would be nice to merge this with the bool/int "simple path" above, although it is slightly different I suppose (but it may actually be faster for the trivially iterable cases, although it may be that we are calling `sum()` at least for bools there for exactly this optimization).

2025-04-22 08:32 UTC, merged