CI: Build using Intel compiler
numpy/numpy pull request #27544
Opened 2024-10-11 21:00 UTC by r-devulap

Addressing https://github.com/numpy/numpy/issues/27492#issuecomment-2401956692

2024-10-11 21:52 UTC, r-devulap commented
crashed and burned, will figure out after the weekend :)

2024-10-16 20:08 UTC, r-devulap commented
> @r-devulap note that SciPy has a working Linux CI job with the Intel LLVM compilers - probably easiest to copy that approach and modify. It's not so easy to get the right things installed with caching etc.

Thanks for that. I will look it up. The workflow in the PR worked locally for me, so hoping this should be okay.

2024-10-17 18:16 UTC, r-devulap commented
yay, finally passed! @AgilentGCMS, any feedback here? Is there anything specific thing you want covered as part of CI?

2024-10-17 21:30 UTC, charris approved these changes

2024-10-18 10:27 UTC, rgommers requested changes
Thanks @r-devulap, good to see this green. I think the test selection is wrong though - this just runs a small subset of tests (__linalg/ufunc/umath tests on Intel TGL_) like for the SIMD tests, but I'd expect it to run the regular test suite instead. And then the job would be better placed in `linux.yml` rather than in `linux_simd.yml`. Is there a reason not to do this?

The build stage looks good. There was one minor issue with warnings for SVML object files, but that's unrelated to this job really so I opened a separate PR to fix that up (gh-27587).

2025-06-11 17:15 UTC, r-devulap commented
Not sure if we really need this, closing for now. Will reopen if we need it at a later stage.

2025-06-11 17:15 UTC, closed without merging