DOC: fix a mistake in the docstring of vector_norm
numpy/numpy pull request #27714
Opened 2024-11-07 14:39 UTC by yuanx749

`ord` in `vector_norm` can be any integer. Also added an example for `ord=0`.
Refer to the table under Notes in [numpy.linalg.norm](https://numpy.org/devdocs/reference/generated/numpy.linalg.norm.html#numpy.linalg.norm).

2024-11-14 15:19 UTC, mdhaber commented on numpy/linalg/_linalg.py
> +    ord : {int, inf, -inf, 'fro', 'nuc'}, optional
This works for vectors, but have you tested with matrices? 
```python3
import numpy as np
x = np.ones((3, 3))
np.linalg.norm(x, ord=0)
# ValueError: Invalid norm order for matrices.
```

2024-11-14 15:21 UTC, mdhaber commented on numpy/linalg/_linalg.py
> +    ord : {int, inf, -inf, 'fro', 'nuc'}, optional
Then again, I suppose it's better to say any int here and clarify later, which the table does. Never mind.

2024-11-14 15:24 UTC, mdhaber commented on numpy/linalg/_linalg.py
> +    ord : {int, inf, -inf, 'fro', 'nuc'}, optional
```suggestion
    ord : {int, float, inf, -inf, 'fro', 'nuc'}, optional
```

2024-11-14 15:29 UTC, mdhaber requested changes
Thanks @yuanx749. I'd suggest some slight additions, then I can merge this.

2024-11-15 01:22 UTC, yuanx749 commented
Thanks for the review @mdhaber . True, any float is ok.

2024-11-15 04:51 UTC, mdhaber approved these changes
LGTM. Thanks @yuanx749!

2024-11-15 04:53 UTC, merged