BUG: Allow any integer type in bincount (fixes #823)
numpy/numpy pull request #4366
Opened 2014-02-26 01:51 UTC by jaimefrio

Gives array-likes that cannot be cast to np.intp a second chance, by
comparing its entries one by one to NPY_INTP_MAX and forcing the cast if
none exceeds it. Fixes #823.

2015-11-28 21:44 UTC, matthew-brett commented
We just ran into this (kind of) problem : https://github.com/nipy/dipy/pull/789 - not bincount, but repeat.

2017-04-10 00:24 UTC, eric-wieser requested changes

2017-04-10 00:24 UTC, eric-wieser commented on numpy/lib/src/_compiled_base.c
> +    while (size--) {
Is it me, or is there no iteration happening here?

2017-04-10 00:24 UTC, eric-wieser commented on numpy/lib/src/_compiled_base.c
> +            PyErr_SetString(PyExc_ValueError,
I think these errors would make more sense emitted by the caller

2020-05-20 20:56 UTC, anirudh2290 commented
@jaimefrio this PR has been stale for a while, do you still want to continue working on this PR ?

2020-12-28 19:25 UTC, charris commented
I'm going to close this, it is stalled and needs rebase. @jaimefrio Please make a new PR if you want to pursue this.

2020-12-28 19:25 UTC, closed without merging