API: Add subok parameter to np.copy function
numpy/numpy pull request #6509
Opened 2015-10-19 02:32 UTC by jjhelmus

The subok parameter determines if sub-classes are passed through.  Setting the argument to True will cause sub-classes, such as MaskedArrays, to be returned after copying.  The default, False, force the copy to be of the base-class, to maintain backwards compatibility.

2016-03-02 16:08 UTC, seberg commented
Sounds reasonable to me (i.e. not much extra clutter ;)) so +0.5 from me. Would need a `.. versionadded::` tag on the new parameter.

2017-02-20 16:14 UTC, eric-wieser requested changes

2017-02-20 16:14 UTC, eric-wieser commented on numpy/lib/tests/test_function_base.py
> +        assert not np.ma.isMaskedArray(np.copy(mx))
Should be using the `assert_` function

2019-02-19 09:57 UTC, OmerJog commented
@jjhelmus are you proceeding with this?

2019-02-19 16:29 UTC, jjhelmus commented
> @jjhelmus are you proceeding with this?

This PR has lingered for too long that I do not recall why the changes were needed.  I'm closing as I do not have the time to reexamine this.

2019-02-19 16:29 UTC, closed without merging