BUG, TST: Fix python3-dbg bug in Travis script
numpy/numpy pull request #8066
Opened 2016-09-20 04:17 UTC by gfyoung

With USE_DEBUG=1, the wrong python was being used to create the `virtualenv`, meaning that installed
packages (e.g. `Cython`) were being installed to the wrong location.  This was discovered in #6936.

2016-09-20 06:33 UTC, gfyoung commented
@charris : Travis and Appveyor are green, so ready to merge if there are no concerns.

2016-09-21 02:49 UTC, gfyoung commented
@charris : Just a signpost for future discussion.  Started in #8071 but should continue here.

2016-09-26 20:17 UTC, gfyoung commented
@charris : Any updates / comments on this one?  This fix does seem straightforward IMHO.

2016-10-09 04:50 UTC, gfyoung commented
@charris : Any updates / comments on this one?  This fix does seem straightforward IMHO.

2016-10-18 01:35 UTC, gfyoung commented
@charris : Any updates / comments on this one?  This fix does seem straightforward IMHO.

2016-10-25 19:09 UTC, gfyoung commented
@charris : Any updates / comments on this one?  This fix does seem straightforward IMHO.

2016-10-25 19:29 UTC, njsmith commented
The actual change makes sense to me. I found the refactoring a bit confusing, though, because of how context is/isn't propagated between different shell scripts -- so e.g. there's this pushd/popd stuff copied into the new before-install script, but it isn't really needed, because working directory changes don't propagate beyond single script, and then there's the need to remember to re-activate the virtualenv each time.

I think it would be simplest to just merge the stuff that's currently in `before_install:` directly into `travis-test.sh`, so we just have one script that does everything.

2016-10-25 19:41 UTC, gfyoung commented
@njsmith : Makes sense to me.  I made a separate commit to test what happens on Travis.

2016-10-25 20:04 UTC, njsmith requested changes

2016-10-25 20:04 UTC, njsmith commented on tools/travis-test.sh
>  set -ex
`set -ex` needs to be the first thing in the file.

2016-10-25 20:04 UTC, njsmith commented on tools/travis-test.sh
> +
Let's put this right next to where we create the venv.

2016-10-25 20:04 UTC, njsmith commented
Travis failed, not sure why.

2016-10-25 21:25 UTC, gfyoung commented
@njsmith : I forgot to copy over the pip installs. :smile:

2016-10-25 21:25 UTC, gfyoung commented on tools/travis-test.sh
> +
Done.

2016-10-25 21:29 UTC, njsmith approved these changes

2016-10-25 21:31 UTC, njsmith commented
Changes look good to me, but Travis is still failing. Maybe send a ping when you've got it passing?

2016-10-25 21:35 UTC, gfyoung commented
@njsmith : Will do.  In the meantime, do you think you could cancel <a href="https://travis-ci.org/numpy/numpy/builds/170595892">#170595892</a>?  It's an old build.  Thanks!

2016-10-25 21:40 UTC, gfyoung commented
@njsmith : So the `chroot` build is failing because some of the commands from `before-travis-install.sh` cannot be run, as can be seen <a href="https://travis-ci.org/numpy/numpy/jobs/170595899">here</a>.  Unless we want to have at it with `linux32`, I am more inclined to keep these original commands separate.

2016-10-25 23:05 UTC, njsmith commented
That failure can be fixed by just telling the shell that we're okay with the information gathering steps at the beginning failing... something like
```
set -x
# It's okay if these fail, and when we run in a chroot they do
uname -a
free -m
ulimit -a
# From here on, we want to know if anything fails
set -e
mkdir builds
...
```
A bigger question is whether it's useful to be running the virtualenv stuff inside a chroot. Potentially the answer is yes, this is actually better... but the chroot handling is confusing enough that I'm not 100% sure :-/. I guess we could make the simple change above and see what happens.

2016-10-26 00:59 UTC, gfyoung commented
@njsmith : Didn't work either.  TBH, I would rather push the patch in first, as I don't see any easy way right now to integrate the two together since the `chroot` seems to mess everything up that `before-travis-install.sh` does.

2016-10-26 01:14 UTC, njsmith commented
Ugh. Well, I guess this is so confusing that we're not making it any worse. (What could possibly go wrong.)

Thanks for sticking with it...

2016-10-26 01:15 UTC, merged