WIP, DOC: Document release procedure with a walkthrough.
numpy/numpy pull request #8106
Opened 2016-10-01 18:18 UTC by charris

This is a walkthrough of a release. I have found it helpful to have the commands laid out in a step by step way so that I can go through line by line. This is preliminary, but does show indicates parts of the procedure that could be further automated and provides a place for comments as well as a handy checklist. It is intended to supplement the expanded content in `doc/HOWTO_RELEASE`.

I'm hoping to foist some releases off on other folks, this should help.

2016-10-01 18:47 UTC, charris commented
@rgommers @ev-br Comments would be helpful. I'm trying to make the actual release process easier to follow.

2016-10-01 21:45 UTC, rgommers requested changes
Thanks Chuck, looks quite useful. My main comments are about the missing step for uploading docs to docs.scipy.org and moving away from SourceForge.

2016-10-01 21:45 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ paver sdist
Maybe add a short comment that ``sdist`` starts with ``git clean -xdf``, so this is OK (doesn't pick up the build artifacts from the last step)

2016-10-01 21:45 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ paver pdf
I think we should move away from SourceForge, so this is not needed anymore then. Now that we don't distribute .exe installers there's really no use for SF anymore, and it has a pretty bad reputation by now (deservedly).

What is missing is the procedure to upload pdf and html docs to docs.scipy.org, which would be good to add instead.

2016-10-01 21:45 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +wheels. You will need to sign every file separately in the process::
Just a note (text is fine): PyPI will likely lose support for signing soon, so this will become simpler.

2016-10-01 21:45 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ cd ../terryfy.git/
should be ``cd ../terryfy``?

2016-10-01 21:45 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ cd ../numpy.git
same here, ``cd ../numpy``

2016-10-01 21:45 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ gvim www/index.rst
add a comment ``# edit the News section``

2016-10-01 21:45 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +The release should be announced on the numpy-devel, scipy-devel, and scipy-user mailing
``numpy-discussion`` not ``numpy-devel``. also, add ``python-announce``

2016-10-01 21:45 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ cd ../scipy.org.git
``cd ../scipy.org``

2016-10-01 22:19 UTC, charris commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ paver pdf
I'll propose dropping sourceforge on the list. We will need to edit some documentation and put a note up on sourceforge. I'll release 1.11.2 there as 1.11.2rc1 is already up.

I don't have permission to upload to docs.scipy.org, how should we deal with that?

2016-10-01 22:20 UTC, charris commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +wheels. You will need to sign every file separately in the process::
Hmm, will there be anything to replace signing, or will it rely on permissions?

2016-10-01 22:22 UTC, charris commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ cd ../terryfy.git/
I append `.git` to git repo directories. I can change that for this documentation. This walkthrough probably needs the layout it is written for documented at the beginning.

2016-10-01 22:22 UTC, charris commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ gvim www/index.rst
Will do.

2016-10-01 22:47 UTC, charris commented
@rgommers Looks like you have stuck yourself with some work by requesting changes, as they are made but apparently you need to sign off on them. Or maybe github can't deal with rewriting history.

2016-10-02 02:25 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +wheels. You will need to sign every file separately in the process::
not sure yet. there was a long discussion about how signing was not very secure in practice anyway. haven't followed the details, but IIRC it'll go away with the switch from the current infrastructure to Warehouse

2016-10-02 02:26 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ paver pdf
we should get you access, but for now you can ping me to do the uploads. we're having a bit of an issue with that server at the moment; all the admins had misplaced their passwords. I have ssh access but no admin rights, so can't add you.

2016-10-02 02:29 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ paver pdf
Instructions are:

    $ make dist    # check that html and pdf docs look right
    $ make upload USERNAME=<username>  # username with ssh access to docs.scipy.org

2016-10-02 02:29 UTC, rgommers approved these changes

2016-10-02 02:31 UTC, rgommers commented
> Looks like you have stuck yourself with some work by requesting changes, as they are made but apparently you need to sign off on them

Hit the button. Looks like a PR can be merged without that approval (which is good, otherwise there's a bottleneck on 1 person), it's just the color stays red until the reviewer who requested changes approved them.

Still getting used to the review functionality, but overall i like it.

2016-10-02 02:33 UTC, rgommers commented
> Still getting used to the review functionality, but overall i like it.

except that now comments that have been addressed aren't hidden on this conversation page....

2016-10-02 02:44 UTC, charris commented
Could get ugly with comments...

I'm not ready to merge this yet, going to add a script for the announcement and a short list of dependencies. At some point should probably cover making the maintenance branch also. Trying to keep text at a minimum though.

2016-10-02 08:31 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ paver pdf
Sorry, that's incorrect. Should be 

    $ make dist    # check that html and pdf docs look right
    $ make upload USERNAME=<username> RELEASE=1.11.2  # username with ssh access to docs.scipy.org

2016-10-02 13:16 UTC, ev-br commented
This looks useful!

I second the suggestion to drop Sourceforge in favor of GH releases. 

Here's my rough draft of a checklist for the last scipy release: https://gist.github.com/ev-br/dd5878cb66aa52e8a548fa7eece55fec
The main difference seems to be that I checksum the wheels locally before uploading them to PyPI. The checksums end up in the README file on GH and in the email announcements.  (Also cf some discussion in https://github.com/MacPython/terryfy/issues/6)

2016-10-03 23:16 UTC, charris commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ paver pdf
Should be possible to put this into paver?

2016-10-04 08:36 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ paver pdf
yep not difficult. The ``USERNAME=<username>`` still needs to be input also then, so won't get much shorter.

2016-10-04 08:37 UTC, rgommers commented
good point @ev-br, +1 for wheel checksums

2016-10-04 15:12 UTC, charris commented
I'll revisit this after the 1.12.0 release. There appear to be two unresolved issues remaining

- Signing/checksumming PyPI uploads
- Documentation

Adding the checksums to the `README.md` could get cumbersome after a while, and it isn't the easiest thing to find. I suppose if the files aren't signed the checksum is needed to check the integrity of the upload.

2016-10-04 17:34 UTC, rgommers commented
Just found another issue: tarballs need to be uploaded to GitHub Releases. Now we get the automatically created tarballs from the release tags, but those are not the same (no generated .c files from cython sources for example).

2016-11-04 23:15 UTC, charris commented
@rgommers How does one upload tarballs to GitHub Releases?

2016-11-04 23:29 UTC, rgommers commented
When you go to https://github.com/numpy/numpy/releases, there's a "draft a new release" button (right top). Click that, then you can edit the description (copy from release notes) and attached files in the UI.

2016-11-04 23:39 UTC, charris commented
@rgommers Thanks. Has the password for documentation upload been found? Also, what documentation gets uploaded, HTML and PDF?

2016-11-04 23:47 UTC, charris commented
@ev-br I don't see the checksums in the README.md on GH. Also, what do you use for the checksum, `shasum -a 256`, `md5sum`, ?

2016-11-05 00:07 UTC, ev-br commented
Other README, here: https://github.com/scipy/scipy/releases
It"s generated by `paver sdist`. When the wheels are ready, I copy them to release/installers folder. Then `paver write_release_and_log` checksums all files in that folder. 
This is scipy's pavement.py file, not sure how different numpy's is.

2016-11-05 00:21 UTC, charris commented
@ev-br Do you find the Changelog useful? I'm thinking of dropping it in favor of the PR links. I note the `Source code` links. Where do they come from?

2016-11-05 00:26 UTC, rgommers commented
> Has the password for documentation upload been found?

Yep, @pv has root access and I have ssh access again.

> Also, what documentation gets uploaded, HTML and PDF?

Yes, those two. See ``make dist``` and ``make upload`` in ``doc/Makefile``.

2016-11-05 00:27 UTC, rgommers commented
> This is scipy's pavement.py file, not sure how different numpy's is.

They're pretty much the same, and differences are probably unintentional.

2016-11-05 00:27 UTC, ev-br commented
Source code links are I believe the useless autogenerated ones that Ralf mentioned. The tar.gz, zip and xz files are uploaded manuallyas binaries  instead.
Changelog, no, I've no uses for it. I always thought it's something downstream integrators use for ... I dunno what :-).

2016-11-05 00:28 UTC, rgommers commented
Changelog I think is just historically the way people did things. No one really looks at it AFAIK.

2016-11-05 00:33 UTC, charris commented
@rgommers So should I get access or should I ping you for that?

2016-11-05 00:44 UTC, rgommers commented
I'm happy to do the uploads (ping me when needed), but getting you access may also make sense. Send @pv your ssh key I guess.

2016-11-17 19:58 UTC, charris commented
@rgommers Do we upload documents for pre-releases?

2016-11-17 20:20 UTC, rgommers commented
no we don't

2016-11-17 21:29 UTC, charris commented
@rgommers Could you document the changes needed in the `index.rst` file of `docs.scipy.org`? Also, would it be better to make that a normal pull request as opposed to simply pushing the result?

2016-11-18 10:24 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ make upload USERNAME=<yourname> RELEASE=1.11.2rc1
remove ``rc1``, we don't upload pre-release docs

2016-11-18 10:25 UTC, rgommers commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +    $ gvim index.rst
Send a PR to https://github.com/scipy/docs.scipy.org with the changes that add links to the new docs. See https://github.com/scipy/docs.scipy.org/pull/7 for an example

2017-03-18 19:09 UTC, ev-br commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +make that easier::
IIRC twine -s signs them all, e.g. `$ twine -s *macosx*whl` only asks for the passphrase once.

2017-03-18 19:22 UTC, charris commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +make that easier::
I thought that also, but vaguely recall it not working. Probably need to test again. In any case, `wheel-uploader` doesn't do that and when I asked @matthew-brett  about it he said they could not get it to work.

2017-03-19 00:38 UTC, charris commented on doc/RELEASE_WALKTHROUGH.rst.txt
> +make that easier::
Might be a function of the twine version. I didn't realize that pip did not automatically upgrade, so was running version 1.6.5.

2017-03-26 17:29 UTC, charris commented
I'm going to merge this now for reference. The documentation section will need revision if/when we move the documents to github.

2017-03-26 17:30 UTC, merged