Added more common example for np.c_
numpy/numpy pull request #8668
Opened 2017-02-22 11:44 UTC by flying-sheep

I mostly use that object to bind 1D arrays as columns, so I added an example for that use case.

2017-02-22 11:49 UTC, eric-wieser requested changes

2017-02-22 11:49 UTC, eric-wieser commented on numpy/lib/index_tricks.py
> +    >>> np.c_[np.array([1,2,3]]), np.array([4,5,6])]
Extra `]` here

2017-02-22 12:49 UTC, eric-wieser commented
Wait, if this passed does that mean we're not running doctests, @charris?

2017-02-22 12:58 UTC, seberg commented
@eric-wieser yup, we have not been running doc tests for years.

2017-02-22 13:10 UTC, eric-wieser commented
@seberg: What was the rationale behind their removal? (And the commit/issue that removed them)

2017-02-22 14:09 UTC, flying-sheep reviewed
ouch, sorry about that blunder

2017-02-22 14:27 UTC, eric-wieser commented
Commits need squashing, and the message should start with `DOC: `

2017-02-22 14:30 UTC, eric-wieser commented
And while you're there, might be nice to add a `See Also` section for `column_stack`

2017-02-22 14:45 UTC, flying-sheep commented
sure, i’ll add the section.

can’t just just squash from github?

2017-02-22 16:33 UTC, eric-wieser commented
Looks good to me

2017-02-22 16:34 UTC, eric-wieser approved these changes

2017-02-22 16:35 UTC, eric-wieser commented
Little concerned about the smart quotes in the commit message. @charris - is this an issue?

2017-02-22 16:39 UTC, charris commented
@eric-wieser doctests are hard to maintain, harder to make both python2 and python3 compatible, depend on the details of formatting, which may change, and generally don't make for good tests. That isn't to say they aren't somewhat maintained as examples, but we don't use them for testing purposes.

2017-02-22 16:41 UTC, eric-wieser commented
>  harder to make both python2 and python3 compatible,

Perhaps we should just enable them on python3 then?

> generally don't make for good tests

They make for good tests for whether the documentation is up to date :)

2017-02-22 16:56 UTC, charris commented
What are the smart quotes?

2017-02-22 16:59 UTC, eric-wieser commented
> DOC: Added “See Also” section for c_

vs

> DOC: Added "See Also" section for c_

Just checking that we have tooling that supports non-ascii characters in commit messages (I assume those are utf8-encoded)

2017-02-22 17:12 UTC, charris commented
IIRC, MIcrosoft uses latin-1 or UTF-16, neither of which is compatible with UTF-8, so it is probably best to stick with the "dumb" quotes.

2017-02-22 17:15 UTC, eric-wieser commented
Apparently git encodes in utf8 automatically, so I think we should be good

2017-02-22 22:40 UTC, merged

2017-02-23 13:22 UTC, flying-sheep commented
great!

2017-02-26 19:56 UTC, ev-br commented
Re doctests: numpy might want to reuse https://github.com/scipy/scipy/blob/master/tools/refguide_check.py