BUG: Fixes histogram monotonicity check for unsigned bin values
numpy/numpy pull request #9294
Opened 2017-06-25 03:16 UTC by b-carter

Add test and fix the monotonicity check to support unsigned bin values, see #9222.

2017-06-25 05:43 UTC, jaimefrio commented on numpy/lib/function_base.py
> +        if not np.all(bins[1:] > bins[:-1]):
I find checks without a negation easier to read, i.e. `if np.any(bins[1:] <= bins[:-1]):`

2017-06-25 05:45 UTC, jaimefrio approved these changes
I have suggested a nitpick, otherwise this LGTM. Thanks!

2017-06-25 06:24 UTC, seberg commented
There are more diff's on the bins further down, do they not matter? What happens if bins is two dimensional? Just out of curiosity to make sure it is an error.

2017-06-26 03:20 UTC, b-carter commented
@jaimefrio I agree, that seems cleaner and maybe more efficient too. I just pushed an update.

@seberg, I'm not sure what you mean by more diff's on the bins further down. Could you give an example? Also, I don't think this breaks anything for the 2D case. It seems that is caught by a ``ValueError: all the input arrays must have same number of dimensions`` from a call to ``sa.searchsorted(bins[-1], 'right')`` on line 796. Maybe there should be an explicit check somewhere else though?

2017-06-26 07:29 UTC, seberg commented
Lines 815 and 822? I don't care what error happens, to be honest, there is likely even a test, if not we could add one. Just wanted to make sure it does not currently silently convert it into a 1D array and we broke it.

2017-06-26 09:52 UTC, eric-wieser requested changes
Behaviour change for repeated bins

2017-06-26 09:52 UTC, eric-wieser commented on numpy/lib/function_base.py
> +        if np.any(bins[1:] <= bins[:-1]):
This isn't equivalent - previously we allowed repeated bins, but this code does not.

I'd prefer `np.any(bins[:-1] > bins[1:])` here, which reads as `current > next`

2017-07-06 14:59 UTC, charris commented
Put the backport milestone off to 1.13.2. Looks like this is close to a fix, be good to finish it up.

2017-08-20 01:13 UTC, b-carter commented
Sorry for the delay, just updated the PR with the suggestion from @eric-wieser.

2017-09-21 19:36 UTC, charris commented
@eric-wieser Are you OK with this?

2017-09-24 20:03 UTC, charris commented
@eric-wieser OK to put this in?

2017-09-24 20:20 UTC, eric-wieser approved these changes

2017-09-24 20:21 UTC, merged

2017-09-24 20:22 UTC, eric-wieser commented
Might be worth flipping the condition to `not all(bins[:-1] <= bins[1:])` to change the nan behaviour, but that's out of scope for this PR.