add additional features to nan_to_num
numpy/numpy pull request #9355
Opened 2017-07-03 13:41 UTC by kikocorreoso

Add some special features to `nan_to_num` in order to allow a user define the values to be used to fill the inexact values.

2017-07-03 16:06 UTC, eric-wieser commented
Note that you can already write this as a single expression with:

```python
np.select([np.isnan(x), np.isposinf(x), np.isneginf(x)], [-999, 999, -999], x)
```

So I'd be inclined not to add yet another way to do it

2017-07-03 17:02 UTC, madphysicist requested changes
I like this PR. It is a simple change that does not break backwards compatibility and gives a good amount of added functionality that I personally find myself needing on occasion. There are a few changes that are necessary to make the function work properly. I would also request that you add some tests for the new functionality (especially one for setting the infs to 0.0).

2017-07-03 17:06 UTC, madphysicist commented
@eric-wieser While I agree with you that there should only be one obvious way to do this, but I think this PR solves a fundamental issue with an existing function. What might be worth doing is replacing that `for` loop with the `select` statement you mentioned, but I think that the changes in and of themselves are useful. In particular, this allows you to not replace the infinities while replacing NaNs, as I mentioned in a previous comment.

2017-07-03 17:27 UTC, eric-wieser commented
Llooking at that for loop - `nan_to_num` has different and frankly weird behaviour for complex variables. 

On the same note, this patch has a bug:

```
>>> np.nan_to_num(no.complex64(nan), nan_fill_value=-999)
-999 - 999j
```

2017-07-03 18:15 UTC, kikocorreoso commented
Thanks @eric-wieser and @madphysicist for your time.

For me `nan_to_num` is very useful but also very limited. The actual state of the PR is just a proof of concept to agree if it is worth to include the extended functionality in numpy.

Pd: I'm not so well versed on numpy and for me the `np.select` way is not so evident :-(

2017-07-03 18:18 UTC, madphysicist commented
Since the function already exists, we may as well improve it. @kikocorreoso, don't worry about not being familiar with `select`. Take your time to play around with it as long as you need until you are happy with how it works. Also, don't forget to write tests for any changes you make!

2017-07-04 10:33 UTC, eric-wieser commented
> The main idea is to allow to [...] use x.astype(np.int32) in a more controlled way specifying the values to use to convert a nan to an int32.

This only creates a trap - all you've solved is controlled casting of `float` to `np.int32` for infinities - large numbers still behave as badly as infinity did:

```
>>> a = np.array([np.inf, np.finfo(float).max]); a
array([              inf,   1.79769313e+308])
>>> a.astype(np.int32)  #not ideal, granted
array([-2147483648, -2147483648])
>>> np.nan_to_num(a).astype(np.int32) # makes no difference
array([-2147483648, -2147483648])
>>> np.nan_to_num(x, posinf_fill_value=-999).astype(np.int32) # with this patch
array([-999, -2147483648])   # only half solves the problem
```

Can you give a more detailed example of the problem you're trying to solve here?

2017-07-05 15:13 UTC, madphysicist commented
@eric-wieser. I see your point and I agree with you. Perhaps a better way to do this would be to introduce a `dtype` parameter, which would default to the type of the input array. You could then spec-out much more clearly how you would want your function to behave for out-of-bounds and NaN elements. I think that would give this function a real reason to exist.

2017-07-05 21:36 UTC, charris commented
Needs rebase.

2017-07-11 06:17 UTC, kikocorreoso commented
Hi all,

I've been busy the latest days and 3 days travelling this week. I hope to come back to this in some days to provide a new PR with the suggestions and use cases.

2019-03-23 19:57 UTC, ahaldane commented
Reviewing this as part of my 10 random issues, as requested in a [3/20/19 request](https://mail.python.org/pipermail/numpy-discussion/2019-March/079250.html).

I like the idea. This just needs to be finished up and rebased. @kikocorreoso are you still available to finish?

To finish, @madphysicist's comments need to be addressed. Also, I personally think the kwd names should be shortened to just 'nan', 'posinf', and 'neginf', so you would do `np.nan_to_num(x, nan=1.0)`.

2019-03-24 09:31 UTC, kikocorreoso commented
Hi @ahaldane 

Yes, I can have a look again on this and try to address all the issues you and @madphysicist commented.

I will try to have a look this week.

2019-03-30 15:59 UTC, kikocorreoso commented
I created a new PR (#13219) as I was not able to figure out how to commit to this one as my original branch was removed.

Please, let me know if I should do it in a more sane way or if I should close this PR and continue the conversation on #13219 .

2019-04-10 06:33 UTC, closed without merging