make `setxor1d' a bit clear and speed up
numpy/numpy pull request #9470
Opened 2017-07-27 03:28 UTC by wufangjie

We need to find the index which is not the same with the left and right, I think np.logical_and's meaning is more clear and I test this got a speed up

2017-07-27 13:40 UTC, jaimefrio requested changes
Thanks, the change LGTM. The existing code was relying on the not obvious property that `flag` can never have two consecutive `False`, so it is indeed much clearer now.

Could you please also:
 * Remove all the commented out code in this function.
 * Add a `MAINT:` prefix to the title of the pull request.

2017-07-27 13:40 UTC, jaimefrio commented on numpy/lib/arraysetops.py
> +    return aux[np.logical_and(flag[1:], flag[:-1])]
I think they are internally translated to the same calls, but I'd day it's more common to use the bitwise operators for boolean arrays, i.e. do `flag[1:] & flag[:-1]`.

2017-07-27 13:49 UTC, eric-wieser commented
This changes the behavior when `assume_unique` is true, but the data isn't. But we probably don't care, and the change might be for the better

2017-07-27 16:15 UTC, jaimefrio commented
It does seem to now also be correct if `assume_unique` is wrongly set to `True`, isn't it?

E.g. if the arrays are `[1, 2, 2, 3]` and `[1, 2, 4]`, after concatenating and joining we would get [1, 1, 2, 2, 2, 3, 4] and the flag array would be `[1, 0, 1, 0, 0, 1, 1, 1]` and we will return the correct `[3, 4]` instead of the incorrect `[2, 3, 4]` currently being returned.

If I'm not missing anything, this then begs the question: is it ever really worth making the first two calls to `unique`, now that it works without them? Unless you have huge amounts of repetition it probably never is...

2017-07-27 16:35 UTC, eric-wieser commented
You're missing the case where the duplicate is only in one set

2017-07-27 18:25 UTC, jaimefrio commented
Ah, right... Too good to be true.

2017-07-27 23:51 UTC, wufangjie commented on numpy/lib/arraysetops.py
> +    return aux[np.logical_and(flag[1:], flag[:-1])]
& is excellent, I forgot np.logical_and is a binary operator sometimes. I'm new to pull request, I did not really understand you two suggestions, it means I should do this next time (you will help me do this time and I don't have to do anything) or I should modify it somewhere, but I can find no way to change the code without a new pull request?

2017-07-28 00:10 UTC, wufangjie commented on numpy/lib/arraysetops.py
> +    return aux[np.logical_and(flag[1:], flag[:-1])]
& is excellent, I forgot np.logical_and is a binary operator sometimes. Learned a lot, thanks.

2017-07-28 08:37 UTC, jaimefrio approved these changes

2017-07-28 08:43 UTC, merged

2017-07-28 08:43 UTC, jaimefrio commented
Seems like you figured out how to make PRs work, in it goes. Thanks @wufangjie!

2017-07-28 10:01 UTC, eric-wieser commented
Not a flaw in this process, but seems like `setxor1d([], [])` crashes

2017-07-28 11:08 UTC, wufangjie commented
setxor1d([], []) will return 0 since aux.size == 0, a few lines before

2017-07-28 11:15 UTC, eric-wieser commented
Right, but flag.shape == (2,), and indexing a (0,) array with a (1,) array is illegal

2017-07-28 11:17 UTC, eric-wieser commented
Ah, nevermind

2017-12-14 00:07 UTC, charris commented
@wufangjie How would you like your name spelled in the release notes?