DOC: added info on shape propery
numpy/numpy pull request #9571
Opened 2017-08-16 07:25 UTC by solarjoe

If someone has more in insight on why it is better not to use y.shape = () directly, please edit the PR.

2017-08-16 15:57 UTC, mhvk commented
@solarjoe - thanks for the PR! Note that the docstring you are editing is for the `shape` property, so it should both describe what it returns (which is the more common case) and what happens if you set it. Also, for a reader it is most helpful if one is very specific: there is certainly nothing "unsafe" about setting the shape. However, unlike `reshape`, it is not always possible (if the strides do not allow the new shape, then `reshape` will make a copy, while setting the shape will fail).

2017-08-16 16:14 UTC, seberg commented
@mhvk "safe" is a matter of thinking here. I know that the masked array code does it all over, which does not make it better. It is unsafe in the sense that nobody expects the array *container* to be a mutable object really, or uses it as such. If you store the same array somewhere else (for whatever reason) and do not specifically create a view there (always a good idea), then the shape of the array might change in a completely unrelated part of the program, e.g.:

```
class MyDataStorage(object):
    def get_data(self):
         return self._data_array

    def calculate_something(self):
        return self._data_array.mean(axis=0)

# Skript:
data = my_data_storage_instance.get_data()
# Oh, I need data reshaped!:
data.shape = (-1, 1)
# Do stuff with data
my_data_storage_array.calculate_something()  # Kaboom
```

Now maybe that object should be returning a view to the data to begin with to avoid possible issues, but in my opinion, our `view` semantics mean that the array as a container should be used as an immutable object while only the data inside the container is mutable. There may be some rare use cases outside this, but I hope those are limited to very specific things.

2017-08-16 17:19 UTC, mhvk commented
@seberg - fair point - but ideally this reason comes through in the docstring; my main suggestion really is to be specific about the difference between setting the shape and using `reshape`.

2017-08-16 18:56 UTC, seberg commented
Yeah, my personal opinion is to be a bit annoying and pester users towards not using this (same goes for setting the dtype), I wouldn't mind trying a deprecation, but I doubt it is doable and there are probably some odd things where it makes sense.

2017-09-23 18:59 UTC, charris requested changes
@mhvk requested changes, so setting that.

2017-10-02 20:51 UTC, charris commented
Closing in favor of #9810. Thanks @solarjoe .

2017-10-02 20:51 UTC, closed without merging